mbta/mobile_app

iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredRouteView.swift

_Ticket:_ none
The iOS build on `main` is broken right now because of a logical merge conflict.
Ran the tests locally.

fix: add nil secondaryAlert to realtime format in filtered stop details

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/UpcomingTripViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyLineViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyStopViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplayTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/UpcomingTripTest.kt

_Ticket:_ [For bus, use Now instead of ARR/BRD](https://app.asana.com/0/1205732265579288/1207678190799457/f)
For bus, don't show `ARR` or `BRD` if the trip is less than or equal to 30 seconds away,  instead show `Now`. Otherwise round to nearest minute.
Added some unit tests, tweaked existing tests, and added a UI test for Android.

fix: Use now instead of ARR/BRD for bus

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/Search/SearchResultView.swift
iosApp/iosApp/Pages/Search/SearchViewModel.swift
iosApp/iosApp/Pages/Settings/Setting+Convenience.swift
iosApp/iosAppTests/Views/SearchResultViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt

_Ticket:_ [Tapping on stop search result goes to Stop Details](https://app.asana.com/0/1205732265579288/1208252548197529/f)
Make it so that stop search results navigate to the associated stop page. Also adds a new feature flag for hiding route search results, and makes it so that search is hidden everywhere except nearby transit.
Added test for tapping stop result rows

feat: Tapping on stop search results navigates to stop page

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/network/MobileBackendClient.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt

_Ticket:_ [[Android] Auto-filter stop details serving one route](https://app.asana.com/0/1205732265579288/1208135554089993/f)
Brings the automatic filtering of the Stop Details view when only one available route and direction are available to Android.
Unit tests for new shared code method.

stop details auto-filtering on Android, move logic to shared code

---

iosApp/iosApp/ContentView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/Map/HomeMapViewHandlerExtension.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsPage.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsStopListSplitView.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsStopListView.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsStopView.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsPageTests.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsStopListSplitViewTests.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsStopViewTests.swift

_Ticket:_ [For bus, use Now instead of ARR/BRD](https://app.asana.com/0/1205732265579288/1207678190799457/f)
Missed changing this for trip details. Turns out we're not passing in `RouteType` to the format function there.
Added a unit test on the affected view for good measure.

fix: show now instead of arr/brd for bus in trip details

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/ObjectCollectionBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TemporaryTerminalRewriter.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TemporaryTerminalRewriterTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TemporaryTerminalTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/UpcomingTripTest.kt

_Ticket:_ [Show only temporary terminals as headsigns during subway shuttles/suspensions](https://app.asana.com/0/1205732265579288/1208057797841305/f)
I really wish we just had correct data upstream. This was initially some of the ugliest code I've written in my life, and it took longer to refactor than it did to write in the first place.
Added tests with real data taken from the recent partial RL closure.

feat: rewrite trips and collapse route patterns during temporary terminals

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/ObjectCollectionBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternsByStop.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt

_Ticket:_ none
_Slack thread_: https://mbta.slack.com/archives/C05QMG9GS9M/p1726766304114719
Oops!
Checked that this fixes the current issue. Added unit tests ensuring that schedules and predictions in the past are correctly filtered out but predictions in the past with vehicles that haven't yet left the stop are correctly retained.

fix: trips that already happened don't count as upcoming

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt

_Ticket:_ [Correctly handle shuttle/suspension boundaries](https://app.asana.com/0/1205732265579288/1207247862893776/f)
I wish I had remembered to check this.
Checked that this fixes the issue, and updated the existing stop details alerts test to also check this.

fix: alert boundaries in stop details

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsRouteViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/RouteFeaturesBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternsByStop.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/PredictionsRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/resolveParentId.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/UpcomingTripTest.kt

_Ticket:_ [Duplicate departure rows for Commuter Rail trips](https://app.asana.com/0/1205425564113216/1207114848419521/f)
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1727112428287779) from different symptoms of the same bug
Matching trips by parent station ID is so clearly the right thing to do that I have no idea why we ever put up with the `flatMap()` in the `RealtimePatterns` constructors.
Added a unit test that would've caught both the new symptom and the old symptom.

fix: match schedules to predictions by parent

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
fastlane/Fastfile
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyViewModel.swift

_Ticket:_ none
We've got pre-commit failures because of Swift symbol issues, we've got Fastlane failures because of the build being rejected, we've got drafts in Google Play that we have to manually push out to even ourselves, our misery is ceaseless. This may fix the first three of those.
I have no idea if upgrading to the latest SwiftFormat will actually fix anything, but I'm not sure what else to try if it doesn't. I also don't know if creating non-draft releases via Fastlane will actually work. I do expect skipping the Fastlane validation to work, though.

ci: fix at least some problems

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopsAssociated.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt

_Ticket:_ Follow up fix for [Handle no service for the entire service day](https://app.asana.com/0/1205732265579288/1208217009015138/f)
In response to [this slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1727187298728979), routes that have major disruptions should still show up in their usual place in nearby transit.
Added a test for sorting behavior with alerts

fix: Don't sort disrupted routes without schedules to the bottom of nearby transit

---

iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/AlertDetails/AlertDetails.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Alert.kt

_Ticket:_ Tangentially related to [Allow for fallback enum values in the backend API parsing code](https://app.asana.com/0/1205732265579288/1207992284641906/f)
Add alert enum cause values which we've gotten sentry errors for.

fix: Add missing alert cause enum values

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/util/SubscribeToPredictionsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/subscribeToPredictions.kt
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/Settings/Setting+Convenience.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/AppVariant.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/PredictionsByStopJoinResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/PredictionsByStopMessageResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/phoenix/PredictionsForStopsChannel.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/PredictionsRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/response/PredictionsByStopJoinResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/PredictionsRepositoryTests.kt

_Ticket:_ [Predictions Scalability: use new predictions channel](https://app.asana.com/0/1205732265579288/1207791938443981/f)
This switches nearby transit & stop details to use the new predictions channel, currently behind a cutover. Temporarily pointing to dev-orange to pick up https://github.com/mbta/mobile_app_backend/pull/203, will remove that before merging.
Added a few unit tests & ran locally to confirm predictions continued to update as expected.

feat: Use new predictions V2 channel behind feature flag

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsRoutesView.kt
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/StopDetails/StopDetailsRoutesView.swift
iosApp/iosAppTests/Pages/AlertDetails/AlertDetailsPageTests.swift
iosApp/iosAppTests/Pages/Map/HomeMapViewTest.swift
iosApp/iosAppTests/Pages/Settings/SettingsPageTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsPageTests.swift
iosApp/iosAppTests/Views/ContentViewTests.swift
iosApp/iosAppTests/Views/HomeMapViewTests.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplayTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/UpcomingTripTest.kt

_Ticket:_ [Show explicitly cancelled bus, CR, ferry trips in departure lists](https://app.asana.com/0/1205425564113216/1207678190799459/f)
Show cancelled trips for non-subway stops when there are more than 2 departures. You'll see I added a lot of `@MainActor` annotations to tests, this was because SwiftUI previews would not work until I did so.
Added some unit tests around new filtering and trip display formatting. Also added new previews to Android and iOS.

fix: show cancelled trips in departure lists

---

iosApp/iosApp/Pages/Map/AnnotatedMap.swift

_Ticket:_ [Make map movement less slippery](https://app.asana.com/0/1205732265579288/1208437030601033/f)
Change how quickly the map decelerates after you fling it with a pan or during a zoom. This prevents the map from feeling slippery and accidentally flinging your location far away from the place you want to be.
Not testable with code, but tried a few values manually to find a comfortable value, and gave it to Paul to demo.

fix: Tweak map pan deceleration

---

iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsView.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsViewTests.swift

No ticket, issue caught while preparing to switch to new predictions channel.
The predictions displayed in the stop details page were not updating as time passed. `now` in `StopDetailsPageView` was updating, but the separate `now` in `StopDetailsView` was not because the `onReceive(of: timer)` was never hit. This change makes `StopDetailsView` use the same `now` as `StopDetailsPageView`. We may want to again consider making an environment object for `now` to use in all places for consistency, but that can be addressed as a larger change. 
* Updated unit tests
* Ran locally and confirmed predictions count down as expected

fix(StopDetails): use updated now throughout child views

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternsByStop.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/PatternsByStopTest.kt

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1728320094267839)
If there are multiple alerts worth showing, we do want to show each of them, but if it's the same alert twice we do not in fact want to show it.
Checked that this fixes the bug as reported. Added a unit test to ensure it stays fixed.

fix: never display alerts twice in filtered stop details

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/PredictionRowView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
iosApp/iosApp/ComponentViews/PredictionRowView.swift
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternSorting.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/PatternSortingTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt

_Ticket:_ [Handle service ended for the day](https://app.asana.com/0/1205425564113216/1208217009015140/f)
Stacked on #445. Implements the display and sorting logic as called for in the task, except for in filtered Stop Details [per Slack](https://mbta.slack.com/archives/C05QMG9GS9M/p1728320849085079?thread_ts=1728320481.516039&cid=C05QMG9GS9M).
Checked manually that this works and added new / updated existing unit tests.

feat: handle service ended today

---

iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitPageViewTests.swift
iosApp/iosAppTests/Views/ContentViewTests.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
iosApp/iosAppTests/Views/SearchResultViewTests.swift

_Ticket:_ none
Most of these are dead code, and the one that wasn't appears to have been intermittently causing crashes elsewhere in the tests, mostly in CI.
Ran the tests.

test: remove all NotUnderTestError declarations

---

iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/Settings/Setting+Convenience.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/PredictionsByStopJoinResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/PredictionsRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt

Ticket: [https://app.asana.com/0/1205732265579288/1207791938443981/f](Predictions Scalability: use new predictions channel)
This removes the predictions V2 channel from behind a feature flag so that all app users will use the new channel. Also removes references to the old channel.
Note: This does not include updating the android client to use the V2 predictions channel - I'll split out a separate ticket for that.
* Repaired unit tests to ensure all use the new channel
* Ran locally to confirm predictions load & update as expected

feat: cutover to use new predictions channel

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsRouteViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/DirectionPicker.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsRoutesView.swift
iosApp/iosAppTests/Pages/StopDetails/DirectionPickerTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsFilteredRouteViewTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsRouteViewTests.swift
iosApp/iosAppTests/Views/HomeMapViewTests.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternsByStop.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt

_Ticket:_ [Handle service ended for the day](https://app.asana.com/0/1205732265579288/1208217009015140/f), kinda
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1728334936690569)
If predictions load before schedules, hasSchedulesToday defaults to true while schedules are loading, so we'll say "Service ended" in places where there are no predictions. Making that default to null won't help if schedules load before predictions; we'll still flash "predictions unavailable" on subway. The most direct way to ensure that we don't make claims about absent service until all the data has loaded is to keep track directly of whether or not all the data has loaded.
Manually verified that everything looks like it's working correctly, updated unit tests, added a new unit test.

fix: show loading instead of service ended when partially loaded

---

iosApp/Podfile.lock
shared/shared.podspec

_Ticket:_ None
Some of the devs were hitting local issues with Sentry versions and pod installs. This was included in #457, but there were issues with the XCode version bump, so instead this just upgrades Sentry.

build(deps): Bump Sentry without upgrading kotlin

---

iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/AlertDetails/AlertDetails.swift

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1728570239748239)
I think I may have just forgotten that this was its own list when I first added service change alert support.
Manually verified that service change alerts have a proper header in alert details.

fix(iOS): display Service Change in alert header

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternSorting.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternsByStop.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TemporaryTerminalTest.kt

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1728582832329829)
This applies temporary terminal rewriting in stop details.
Checked that all unit tests still pass. Manually verified that temporary terminals are rewritten in Nearby Transit and in Stop Details. Added Stop Details to the temporary terminal integration tests.

refactor: unify stop details with nearby transit

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/util/SubscribeToPredictionsTest.kt
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsPage.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsPageTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/PredictionsRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/TripPredictionsRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/PredictionsRepositoryTests.kt

_Ticket:_ [[Loading states] Clear predictions when older than 10 minutes](https://app.asana.com/0/1205732265579288/1208468599574698/f)
My first draft had all the logic in the `onActive` callbacks, but there's enough of it that it makes sense to move it into the shared code.
Manually verified that predictions are forgotten after ten minutes but not after nine minutes. Added unit tests for the logic in shared code; I'm not sure how straightforward it'd be to test the scene phase handlers, but if it's worth a look I can try.

feat(iOS): forget predictions if backgrounded for over ten minutes

---

iosApp/iosAppTests/Views/ErrorBannerTests.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift

No ticket, addresses some test failures creeping in
This addresses some test flakiness that is creeping in, such as in https://github.com/mbta/mobile_app/pull/464. In https://github.com/mbta/mobile_app/pull/293 we found that increasing the wait to 1 second fixed the flakiness we were seeing. Trying a bump to 0.5.

chore: increase test waits to address flakiness

---

iosApp/iosApp/Pages/Map/HomeMapView.swift
iosApp/iosApp/Pages/Map/HomeMapViewHandlerExtension.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/RouteFeaturesBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/phoenix/VehiclesOnRouteChannel.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/VehiclesRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/phoenix/VehiclesOnRouteChannelTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/VehiclesRepositoryTest.kt

_Ticket:_ [Green Line vehicles don't load in filtered Stop Details](https://app.asana.com/0/1205732265579288/1207813918309501/f)
We needed to be able to load vehicles for multiple routes in order to display GL vehicles before, which wasn't possible on the backend before https://github.com/mbta/mobile_app_backend/pull/214. This switches the vehicles channel to use that new multi-vehicle topic, and adds some additional filtering to only display the vehicles on routes which match the displayed route shapes on the map. 
Added unit tests in shared code.

fix: Display GL vehicles on filtered stop page

---

iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Direction.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/ObjectCollectionBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternsByStop.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/DirectionTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/PatternsByStopTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt

_Ticket:_ [GL showing duplicate Eastbound @ Gov Center with no data](https://app.asana.com/0/1205732265579288/1208378317839446/f)
Most of the added lines here are in the tests, sorry for the large PR! 😅 
After #454, there were issues introduced where we would only ever display grouped nearby headsigns on the Medford/Tufts branch. This changes the headsign grouping to split grouped routes into separate headsigns if only a single route pattern is predicted in one direction. This means that it's technically possible (but very unlikely) for a grouping to be displayed when an atypical trip is predicted but has multiple other predictions before it and so wouldn't be displayed in nearby, but since this only applies to a stretch of 5 stops that rarely have more than 2 trains headed inbound at any …

fix: Show correct headsigns and groupings on all GL branches

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ComponentViews/RouteIcon.swift
iosApp/iosApp/ComponentViews/SheetHeader.swift
iosApp/iosApp/ComponentViews/TransitHeader.swift
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/TripDetails/TripDetailsHeader.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsStopListSplitView.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsStopView.swift
iosApp/iosApp/Pages/TripDetails/VehicleCardView.swift
iosApp/iosApp/Utils/RouteTypeExtension.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsStopViewTests.swift

_Ticket:_ [Optimize Trip Details screen reader text](https://app.asana.com/0/1205732265579288/1208295417175124/f)
Updates the Trip Details page to use accessible elements and headings for improved VoiceOver access.
Manual testing in the Accessibility inspector. Unfortunately I can't find a way to test accessibility labels and elements through the unit tests.

Jvc trip details screen reader text

---

iosApp/iosApp/ComponentViews/LineHeader.swift
iosApp/iosApp/ComponentViews/PinButton.swift
iosApp/iosApp/ComponentViews/RouteHeader.swift
iosApp/iosApp/ComponentViews/RoutePill.swift
iosApp/iosApp/ComponentViews/TransitHeader.swift
iosApp/iosApp/Pages/StopDetails/DirectionPicker.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilterPills.swift

_Ticket:_ [Optimize Stop Details screen reader text](https://app.asana.com/0/1205732265579288/1208295417175122/f)
Improves Stop Details accessibility for VoiceOver users.
NB: One area where I deviated from the Figma spec is in the DirectionPicker. Figma has the number of options repeated as part of the input, e.g. "option 1 of 2"; however, when I added a native Picker as a test, that content was not presented. I therefore opted to leave it out of the DirectionPicker accessibility text. See screenshots:
Native Picker:
Custom DirectionPicker:
Manual testing with Accessibility Inspector

Optimize Stop Details screen reader text

---

iosApp/iosApp/ContentView.swift
iosApp/iosApp/Pages/Settings/Setting+Convenience.swift
iosApp/iosApp/ViewModels/ContentViewModel.swift
iosApp/iosAppTests/Pages/Settings/SettingsPageTests.swift
iosApp/iosAppTests/Views/ContentViewModelTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt

_Ticket:_ [Take search out from behind feature flag](https://app.asana.com/0/1205732265579288/1208355161933409/f)
Remove search from behind feature flag.
Manual testing, fixed existing tests.

fix: remove search feature flag

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/UpcomingTripViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/getSchedule.kt
iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ComponentViews/RealtimeIndicator.swift
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/ComponentViews/WithRealtimeIndicator.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Utils/Typography.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsPageTests.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsStopViewTests.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
iosApp/iosAppTests/Views/UpcomingTripViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Prediction.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplayTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/UpcomingTripTest.kt

_Ticket:_ [Update real-time indicator](https://app.asana.com/0/1205732265579288/1208468599574768/f), [Fix: Bus trip details show minutes, not timestamps](https://app.asana.com/0/1205732265579288/1208468599574706/f)
Add realtime indicators next to realtime predictions, remove schedule clock icon, show only clock times for CR and ferry, and restyle displayed schedules to be greyed out. Also fixes trip details for bus showing countdown times because I was updating that code already.
Added and updated tests to match the new behavior.

feat: Add realtime indicators next to predictions

---

iosApp/ci_scripts/ci_post_clone.sh

_Ticket:_ [Retry ci_post_clone script steps if failures](https://app.asana.com/0/1205425564113216/1208581804426730/f)
The fact that we can't retry PR builds when they fail means this is suddenly much higher priority.
Checked the `retry` function locally (and caught an error in my shell syntax).

ci: retry network commands

---

iosApp/iosApp/ContentView.swift
iosApp/iosApp/Pages/Settings/Setting+Convenience.swift
iosApp/iosApp/Pages/Settings/SettingsSection.swift
iosApp/iosApp/ViewModels/ContentViewModel.swift
iosApp/iosApp/ViewModels/SettingsViewModel.swift
iosApp/iosAppTests/Views/ContentViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt

_Ticket:_ [Setting to hide maps](https://app.asana.com/0/1205732265579288/1208572284247927/f)
As I expected, the way we broke up the ContentView makes this not difficult at all to implement.
Added a unit test. Manually validated that everything behaves reasonably (including with VoiceOver) and [checked in Slack](https://mbta.slack.com/archives/C05QMG9GS9M/p1729711383158839) that no changes need to be made.

feat(iOS): add option to hide maps

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/util/GetGlobalDataTest.kt
gradle/libs.versions.toml
iosApp/iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/AlertDetails/AlertDetailsPage.swift
iosApp/iosApp/Pages/Map/HomeMapView.swift
iosApp/iosApp/Pages/Map/HomeMapViewHandlerExtension.swift
iosApp/iosApp/Pages/Map/HomeMapViewLayerExtension.swift
iosApp/iosApp/Pages/Map/MapLayerManager.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/Utils/FetchApi.swift
iosApp/iosApp/ViewModels/MapViewModel.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosApp/ViewModels/SearchViewModel.swift
iosApp/iosAppTests/Pages/AlertDetails/AlertDetailsPageTests.swift
iosApp/iosAppTests/Pages/Map/MapViewModelTests.swift
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitPageViewTests.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsPageTests.swift
iosApp/iosAppTests/Views/HomeMapViewTests.swift
shared/build.gradle.kts
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/cache/ResponseCache.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/GlobalRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/cache/ResponseCacheTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/GlobalRepositoryTest.kt
shared/src/iosMain/kotlin/com/mbta/tid/mbta_app/utils/SystemPaths.ios.kt
shared/src/iosTest/kotlin/com/mbta/tid/mbta_app/utils/SystemPathsTest.ios.kt

_Ticket:_ [Make cached data flow through a stream](https://app.asana.com/0/1205732265579288/1208254208398831/f)
This makes it possible for stale cached data to be displayed to the user while the API request is being performed to check whether or not the data is still stale. This will allow users on slow internet connections to see data earlier, and once 
[Cache route shape requests](https://app.asana.com/0/1205732265579288/1208254208398835/f) is completed, it will display map layers quickly on slow internet connections, and prevent blank maps when either request fails.
This also turned into a bit of a hunt for map performance issues in general, I moved a bunch of the map source and layer logic into tasks to prevent as much logic as possible from happening on the main thread and freezing …

fix: Consume global data from a flow

---

iosApp/iosApp/Fetchers/ViewportProvider.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitPageView.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1729783255982609)
Treats the recenter button like panning the map, and forgets stale data in both cases.
Manually verified that this works.

fix(iOS): show loading state on recenter

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplayTest.kt

_Ticket:_ [Fix: old cancelled trips appearing in filtered stop details](https://app.asana.com/0/1205732265579288/1208468599574761/f)
Hides old cancelled trips in stop details
* Added a unit test
* Confirmed before & after - cancelled trip in past no longer shows up on the 86

fix(TripInstantDisplay): Hide past cancellations

---

iosApp/iosApp/ContentView.swift
iosApp/iosApp/Pages/More/MorePage.swift

_Ticket:_ [More tab](https://app.asana.com/0/1205732265579288/1208468599574774/f)
There was a visual bug when navigating to the More page where the area that the sheet was in would display as a blank rectangle on top of the more page, then flash away. This explicitly tells the sheet to hide when navigating to more, which causes it to animate away when navigating.
Verified the expected behavior on a physical device.

fix: Make sheet animate away on nav to more

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ComponentViews/LocationAuthButton.swift
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosAppUITests/HomeMapViewUITests.swift

_Ticket:_ [Location services button](https://app.asana.com/0/1205732265579288/1208304466486202/f)
Adds a button to link the user to Settings when Location functionality is disabled.
UI test for the button and alert popup

Location Services Button

---

iosApp/iosApp/ContentView.swift

_Ticket:_ [None, quick bug fix]
Fixes the alignment of the Recenter button on the map. Currently it is pulled to the center alongside the Location Services button. 
Before:
After:

correct the alignment of the recenter button

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ComponentViews/ActionButton.swift
iosApp/iosApp/ComponentViews/DirectionLabel.swift
iosApp/iosApp/ComponentViews/ErrorBanner.swift
iosApp/iosApp/ComponentViews/ErrorCard.swift
iosApp/iosApp/ComponentViews/LoadingCard.swift
iosApp/iosApp/ComponentViews/LocationAuthButton.swift
iosApp/iosApp/ComponentViews/PinButton.swift
iosApp/iosApp/ComponentViews/PredictionRowView.swift
iosApp/iosApp/ComponentViews/PredictionText.swift
iosApp/iosApp/ComponentViews/UpcomingTripAccessibilityFormatters.swift
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/AlertDetails/AlertDetails.swift
iosApp/iosApp/Pages/AlertDetails/AlertDetailsPage.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitPageView.swift
iosApp/iosApp/Pages/Onboarding/OnboardingScreenView.swift
iosApp/iosApp/Pages/Search/SearchField.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilterPills.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsHeader.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsStopListSplitView.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsStopView.swift
iosApp/iosApp/Pages/TripDetails/VehicleCardView.swift
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitPageViewTests.swift
iosApp/iosAppTests/Pages/Onboarding/OnboardingScreenViewTests.swift
iosApp/iosAppTests/Pages/TripDetails/VehicleCardViewTests.swift
iosApp/iosAppTests/Views/LoadingCardTests.swift

_Ticket:_ [Fill in missing comments for translators](https://app.asana.com/0/1205732265579288/1208643843115469/f)
Stacked onto #503 
Audited all strings in the app, I added a dummy language with all strings replaced with a specific character to make sure that everything was being properly translated, and updated a handful of places that weren't being replaced. I also tested using VoiceOver, in both english and the dummy language, to make sure all of the accessibility text was also being properly localized. Also added comments to any potentially ambiguous strings, and cleaned up some copy that snuck through the cracks.
Manual testing with alternate locales and VoiceOver

i18n: Add missing strings for localization

---

iosApp/iosApp/ContentView.swift
iosApp/iosApp/Fetchers/ViewportProvider.swift
iosApp/iosAppTests/Fetchers/ViewportProviderTest.swift

_Ticket:_ [Location doesn't update when Hide Maps is turned on](https://app.asana.com/0/1205732265579288/1208660630503484/f)
Fix an issue where the current location was never updating the nearby transit location when "Hide Maps" was toggled on.
Added a test for new ViewportProvider helper function

fix: Fix hide maps location changes

---

iosApp/iosApp/ComponentViews/PredictionText.swift
iosApp/iosApp/Localizable.xcstrings

Raised during app QA, prediction times were no longer being bolded because of how translations were changed.

fix: Fix bolded prediction times

---

iosApp/iosApp/ComponentViews/DirectionLabel.swift

_Ticket:_ [Fix alignment of multi-line headsigns in direction toggle](https://app.asana.com/0/1205425564113216/1208672143544735/f)
Properly align direction destination labels

fix: Properly align multi line direction text

---

iosApp/iosApp/Localizable.xcstrings

@boringcactus flagged a few more possible prediction status text overrides we can get for CR. We're not handling them yet, but we want to include them in the localization file we send to the translators so that they're ready when we do.

i18n: Add possible CR status override strings

---

iosApp/iosApp/ContentView.swift
iosApp/iosAppTests/Views/ContentViewTests.swift

Hotfix, no ticket
This PR fixes an issue where after the onboarding flow, users would get stuck on a shimmer loading screen. 
The cause was that by the time the nearby transit sheet popped after onboarding, there was no scene phase to trigger joining. Moved to the top of the view hierarchy so that it is always called on app startup.
Tested locally & updated existing unit tests. I moved the map config handling logic to the same top level because fiddling with the list of `implicitAnyViews` was giving me trouble.

fix: always join alerts on app startup

---

iosApp/iosApp/Pages/AlertDetails/AlertDetails.swift
iosApp/iosAppTests/Pages/AlertDetails/AlertDetailsPageTests.swift
iosApp/iosAppTests/Pages/AlertDetails/AlertDetailsTests.swift

Raised during app QA, markdown formatting was somehow broken after adding a Text comment.

fix: Fix formatting of alert details text

---

iosApp/iosApp/ComponentViews/DirectionRowView.swift
iosApp/iosApp/ComponentViews/HeadsignRowView.swift
iosApp/iosApp/Pages/NearbyTransit/StopDeparturesSummaryList.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredRouteView.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsStopView.swift

No ticket. Took a quick look at voice control for nearby transit and noticed that saying "Tap Braintree" didn't automatically work - you then had to say "Tap 3". It seems like the accessibilityInputLabel was applying to each child element individually and creating 3 duplicate labels. 
There may be a cleaner approach than this, but it made sense to me to move the label to the button itself.
* Ran with Voice Control on, confirmed I could say just "Tap Braintree" to navigate from Nearby => Stop Details, "Tap Braintree" from Stop Details => Trip Details, and "Tap Park" From Trip Details => Stop Details
* Ran with Voice Over on and confirmed elements still read as expected

fix(VoiceControl): accessibilityInputLabel for links within sheet

---

iosApp/iosApp/Localizable.xcstrings

_Ticket:_ [Import second batch of translations](https://app.asana.com/0/1205732265579288/1208742518780611/f) (added)
This adds the translations for the second batch of strings sent. There was one remaining string that was missing translations, which I manually added.
Ran locally in Spanish, confirmed I see newly translated strings

feat(localizable): Another batch of translations

---

iosApp/ci_scripts/ci_post_clone.sh

_Ticket:_ none
Builds on `main` are failing right now, and from the error message I think this is why.
When I get the same error message locally, this is how I fix it, but I have no idea if it'll fix the non-test Xcode Cloud targets until we merge this (unless we want to temporarily add archive or analyze to the PR workflow).

fix: ensure gradle knows pods are installed

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopListTest.kt

_Ticket:_ [[duplicate prediction bugfix]](https://app.asana.com/0/1205732265579288/1208788669093055/f)
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1731701471451859?thread_ts=1731524220.060079&cid=C05QMG9GS9M)
Fixes a bug where multi-route trips with duplicated predictions on each route were causing trip details to crash since the logic there can't actually handle redundant predictions with the same stop sequence.
I'm hoping that there aren't secretly cases where this will cause problems of its own - I don't think it should be possible for there to be predictions on the wrong route without corresponding predictions on the right route.
Validated that this fixes the bug as reported. Added a unit test to detect regressions.

fix: don't crash opening trip details on a multi-route trip

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TemporaryTerminalFilter.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TemporaryTerminalFilterTest.kt

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1731950568783199)
Updated existing unit tests to still pass. Added a new unit test to check new functionality.

fix: don't filter out temporary terminal if predictions suppressed

---

shared/build.gradle.kts
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/style/FeatureProperties.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/ObjectCollectionBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Stop.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/TripSchedulesResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/NearbyRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/map/StopFeaturesBuilderTest.kt

_Ticket:_ [Fix missing trip crash ](https://app.asana.com/0/1205732265579288/1208639731566258/f)
Removes all calls to Map.getValue in shared code, and adds a custom Spotless lint to ensure we don't add any more in the future.
I'm not quite sure if adding the Spotless lint is worth it - if it fails, it'll fail in the pre-commit step rather than somewhere more visible, and if we need to call a different function that is coincidentally also named getValue, this'll make that really annoying.
Ensured that all shared unit tests still pass.

fix: never call Map.getValue in shared code

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/util/SubscribeToPredictionsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/SocketMessage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/subscribeToPredictions.kt

_Ticket:_ [Use predictions v2 channel in Android app](https://app.asana.com/0/1205732265579288/1208501775350660/f)
Use the same, more scalable endpoint as iOS for the predictions real time data. This PR also fixes a parsing issue with the `decodeRawMessage` function.

use predictions v2 and fix bug in decodeRawMessage

---

iosApp/iosApp/ComponentViews/DebugView.swift
iosApp/iosApp/ComponentViews/ErrorBanner.swift
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsView.swift
iosApp/iosApp/Pages/TripDetails/TripDetailsPage.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsViewTests.swift
iosApp/iosAppTests/Pages/TripDetails/TripDetailsPageTests.swift

_Ticket:_ [Debug setting to show (trip, stop, vehicle, etc) IDs](https://app.asana.com/0/1205732265579288/1208629979901034/f)
This PR adds the low hanging fruit ids - trip, stop, and vehicle. I opted to add each element in the detail view (stop in stop details, trip & vehicle in trip details). 
I didn't add anything around route patterns since our route pattern grouping logic is in flux - if we find it will be valuable, we can add that separately. I did take an initial pass at it and it would involve quite a bit of prop drilling unless we switch to using an EnvironmentObject to represent debug mode.
Added some unit tests & ran locally. Also checked formatting to address the DebugView expanding unexpectedly as raised [in …

feat(DebugView): trip, stop, vehicle ids

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredRouteViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsRoutesViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/StopDetailsPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsView.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosApp/ViewModels/SettingsViewModel.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyHierarchy.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/ObjectCollectionBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternsByStop.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TemporaryTerminalTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/UpcomingTripTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepositoryTest.kt

_Ticket:_ [Use trip headsigns in Nearby Transit](https://app.asana.com/0/1205732265579288/1208759166078934/f)
It probably makes sense to keep this behind a feature flag for a bit.
Manually verified that the new logic works correctly. Made existing unit tests parametric to check both old and new code paths. Added a new unit test to ensure that the new code path delivers on its stated goals.
I have not written unit tests that directly check the NearbyHierarchy itself; I could do that, but this PR is already too large.

feat: rearchitect everything to use trip headsigns

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt
iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Fetchers/ViewportProvider.swift
iosApp/iosApp/Pages/AlertDetails/AlertDetailsPage.swift
iosApp/iosApp/Pages/LegacyStopDetails/LegacyStopDetailsPage.swift
iosApp/iosApp/Pages/LegacyStopDetails/LegacyStopDetailsView.swift
iosApp/iosApp/Pages/LegacyStopDetails/StopDetailsFilteredRouteView.swift
iosApp/iosApp/Pages/Map/AnnotatedMap.swift
iosApp/iosApp/Pages/Map/HomeMapView.swift
iosApp/iosApp/Pages/Map/HomeMapViewHandlerExtension.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPageHandlerExtension.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsView.swift
iosApp/iosApp/Pages/StopDetails/TripDetailsView.swift
iosApp/iosApp/Utils/SheetNavigationStackEntry.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsViewTests.swift
iosApp/iosAppTests/Views/ContentViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsFilter.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/VehiclesRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt

_Ticket:_ [Combined stop + trip details: barebones UX](https://app.asana.com/0/1205732265579288/1208725410378675/f)
Stacked onto #554 
This takes the existing trip details page and inserts it into the existing stop details page. Also updates the map to display the stop and vehicle whenever the vehicle filter changes.
~- [ ] If you added any user facing strings on iOS, are they included in Localizable.xcstrings?~
Added tests for new views and kotlin methods, confirmed behavior with feature toggle on and off

feat: Combine existing trip details into new combined stop page

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPageHandlerExtension.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsView.swift
iosApp/iosApp/Pages/StopDetails/TripDetailsView.swift
iosApp/iosApp/Utils/ScenePhaseChangeModifier.swift
iosApp/iosApp/ViewModels/StopDetailsViewModel.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsViewTests.swift

_Ticket:_ [Combined stop + trip details: departure list UI](https://app.asana.com/0/1205732265579288/1208725410378678/f)
Discussed in https://github.com/mbta/mobile_app/pull/551#discussion_r1854636220, this moves a chunk of the logic in the stop details extension into a new stop details VM. I didn't include any logic that touched other VMs (nearby and errordetails), so about half of the logic still lives in the extension.
This should probably also include any required trip details calls, but we can do that as part of [Combined stop + trip details: Trip details UI](https://app.asana.com/0/1205732265579288/1208725410378682/f).
~- [ ] If you added any user facing strings on iOS, are they included in Localizable.xcstrings?~
Updated tests to use the VM instead of passing repos directly into …

refactor: Move some stop details logic into a VM

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/more/MoreSectionViewTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/more/MoreViewModelTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/MorePageTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/LabeledSwitch.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreSectionView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MorePage.kt
androidApp/src/main/res/values/strings.xml
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/morePage/MoreItem.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/morePage/MoreSection.kt

_Ticket:_ [🤖 | More | Expose feature flags in settings](https://app.asana.com/0/1205732265579288/1208839363050252/f)
This PR add settings and feature flags to the more page for Android. Follows the same structure as the more page in iOS.
Wrote unit tests, ran locally and confirmed I could toggle settings as expected

feat(MorePage): Settings & feature flags

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt

_Ticket:_ [Update lookahead from 90 to 120 minutes](https://app.asana.com/0/1205732265579288/1208643635653118/f)
There are no longer references to 90 minutes anywhere in the app.
iOS
android
Updated the unit tests. Did not spend a ton of time trying to find a case where a pattern is filtered in at 120 minutes that was filtered out at 90, but it should be fine.

feat: extend non-typical upcoming cutoff to 120 min

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt

_Ticket:_ [🤖 | Map | Mapbox styles updated](https://app.asana.com/0/1205732265579288/1208852051039921/f)
I wish every ticket was this easy.
iOS
android
Verified that the map looks different on the current staging build than it does on this branch.

feat(Android): use custom map styles

---

iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
iosApp/iosApp/Pages/StopDetails/TripStops.swift

_Ticket:_ No ticket, [slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1734017693325669)
Anna brought up in slack that the separate inner scroll container for the trip stops wasn't ideal and requested that the whole page scroll under the header instead.
iOS
~- [ ] If you added any user-facing strings on iOS, are they included in Localizable.xcstrings? ~
~  - [ ] Add temporary machine translations, marked "Needs Review"~
android
~- [ ] All user-facing strings added to strings resource~
Manual testing to ensure that the new scroll behavior works as intended

fix: Move scrolling to encompass entire stop page

---

androidApp/build.gradle.kts
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/res/resources.properties
androidApp/src/main/res/values-b+es/strings.xml
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
buildSrc/src/main/kotlin/com/mbta/tid/mbta_app/gradle/ConvertIosLocalizationTask.kt

_Ticket:_ [🤖 | Determine localization approach](https://app.asana.com/0/1205425564113216/1208790341716788/f)
I couldn't find any obviously useful automated tools for converting between iOS Localizable.xcstrings and Android string resources, but it turns out it's fairly straightforward to staple something basic together myself.
Tradeoffs:
- I'm using the iOS format as the source of truth here, because there's nothing in Android that can explicitly represent the "Needs Review" state that our workflow relies on.
- Instead of generating Android IDs for new iOS strings eagerly, this will only copy translations for strings which are already defined on Android in English. This is both easier and more useful, since it lets us pick manually what ID makes the most sense.
- The iOS string templating …

feat: convert iOS translations to Android format

---

androidApp/build.gradle.kts
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/ContentViewTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/DirectionPickerTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/HeadsignRowViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/PinButtonTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/RouteHeaderTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/ActionButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/AlertIcon.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/BottomNavIconButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/DirectionLabel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/PinButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/PredictionRowView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/RouteIcon.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/TransitHeader.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/RecenterButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
buildSrc/src/main/kotlin/com/mbta/tid/mbta_app/gradle/ConvertIosLocalizationTask.kt

_Ticket:_ [🤖 | Localization catchup](https://app.asana.com/0/1205732265579288/1208936978928073/f)
Since we are using the iOS side as the source of truth after all, this task is easy.
android
Verified that the new labels appear properly.

fix(Android): internationalize all hardcoded text

---

iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsUnfilteredView.swift
iosApp/iosApp/Utils/SheetNavigationStackEntry.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsViewTests.swift
iosApp/iosAppTests/Utils/SheetNavigationStackEntryTests.swift
iosApp/iosAppTests/ViewModels/NearbyViewModelTests.swift

_Ticket:_ [Combined Stop + Trip Details: nav changes](https://app.asana.com/0/1205732265579288/1208725410378683/f)
This updates the combined stop/trip navigation to match the desired behavior. Back buttons are removed from the filtered and unflitered stop pages, and the X button on filtered stop details will bring you back to the place you came from, either the unfiltered stop or nearby transit. Because this doesn't involve changing the actual entry type, but just the stop filter on the entry, there's some slightly convoluted logic to ensure that filter entries are appended rather than replacing the unfiltered entry, and that when the filtered entries are removed, that they don't add duplicate unfiltered entries. This logic also unfortunately needs to exist in two places, since a new …

feat: Update stop details navigation to match spec

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/MapViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt

_Ticket:_ [Data parsing crash on backgrounding](https://app.asana.com/0/1205732265579288/1208885747081174/f)
Resolves the crashes that occur when backgrounding the app.
iOS
android
No logic changes, just shuffling data around into a view model. Not sure if there's a way to automate lifecycle testing.

fix: parcel crash, move data/functions to VM

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToAlertsTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToPredictionsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToAlerts.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToPredictions.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/AlertsRepository.kt

_Ticket:_ [🤖 | Stability | Leave realtime channels when backgrounding](https://app.asana.com/0/1205732265579288/1208725410378690/f)
Follow-up to https://github.com/mbta/mobile_app/pull/579, applies the same pattern to predictions & alerts. 
iOS
android
* Ran locally, confirmed I can background & revive the app without crashing
* Updated unit tests

feat(android): leave / rejoin predictions & alerts after backgrounding

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt

_Ticket:_ [🤖 | Nearby | Sheet / navigation](https://app.asana.com/0/1205732265579288/1208852051039919/f)
Apparently the Android stock navigation subsystem is just this flexible.
I haven't been able to see this animation play back smoothly at its default speed because we drop frames pretty badly on the page transition, but if I slow it way down then I do briefly see smooth motion. I don't think that frame loss is in-scope for this PR, but I may look into it separately.
iOS
android
Manually validated that the animation should theoretically play.

feat(Android): animate new page sliding up

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/sheet/AnchoredDraggable.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/sheet/BottomSheetScaffold.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/sheet/SheetDefaults.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt

_Ticket:_ [🤖 | Nearby | Sheet / navigation](https://app.asana.com/0/1205732265579288/1208852051039919/f)
There is [a third-party library](https://github.com/skydoves/FlexibleBottomSheet) that we could consider instead, but it's got outstanding issues that haven't been so much as acknowledged for months, and it doesn't provide an equivalent to the full Scaffold component, so we'd need to copy in some of the Layout stuff anyway. (I also didn't check for this until after I had already done most of this work.)
iOS
android
Manually verified that the new sheet has all three sizes and that the Mapbox attribution footer is in the right place at the sizes where the map is visible.

feat(Android): allow small sheet size

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/StopDetailsFilterPillsTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/SheetHeader.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilterPills.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings

_Ticket:_ [🤖 | Unfiltered Stop Details | Screen reader text](https://app.asana.com/0/1205732265579288/1208851006555185/f)
* Adds screen reader optimizations for unfiltered stop details - mainly the filter buttons.
iOS
android
* Ran locally with talk back on
* Added some unit tests

feat(android.StopDetailsFilterPills): optimized screen reader text

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NoNearbyStopsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/location/ViewportProvider.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NoNearbyStopsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt

_Ticket:_ [🤖 | Map | Hide maps functionality](https://app.asana.com/0/1201654106676769/1208851802887624/f)
Stacked on #618 since the acceptance criteria specify that the location services button is in-scope for this ticket.
iOS
android
Manually validated that everything looks correct with hide maps turned on, except for the stop details page, which looks wrong and needs to be fixed before this PR is actually ready for review. Added a unit test to check that maps are correctly hidden and shown.

feat(Android): hide maps

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetNearbyTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getNearby.kt
iosApp/iosApp/Utils/CoordinateExtension.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Coordinate.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/NearbyRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/NearbyRepositoryTest.kt

_Ticket:_ [🤖 | Nearby | Reset state when panning or recentering](https://app.asana.com/0/1205732265579288/1208915825996354/f), tangentially
We should probably have caught this a while back, but we're already using the Spatial K Position in enough other places in `shared` that it doesn't make sense to also have our own `Coordinate` for just this one use case.
iOS
android
Checked that all related unit tests pass on Android and iOS.

fix: replace Coordinate with Position in NearbyRepository

---

buildSrc/build.gradle.kts

Reverts mbta/mobile_app#624
This started breaking iOS builds, this file wasn't set to run the iOS workflows, so there wasn't an indication in the PR that anything was wrong.

Revert "build(deps): bump org.cyclonedx:cyclonedx-core-java from 9.0.5 to 10.1.0"

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/ErrorBannerTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlayTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToPredictionsTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/ErrorBanner.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/ErrorBannerViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/IndeterminateLoadingIndicator.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/StopDetailsPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getGlobalData.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getSchedule.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToPredictions.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/fetchApi.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml

_Ticket:_ [🤖 | Nearby | Display error banners](https://app.asana.com/0/1205732265579288/1208968297244757/f)
Adding the error banner on Android for nearby transit.
iOS
android
Added previews and automated tests for various error banner states.

feat(Android): error banner

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlayTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetSearchResultTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/Routes.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/BottomNavBar.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlay.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/StopResultsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getSearchResults.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml

_Ticket:_ [🤖 | Search | Search recently visited](https://app.asana.com/0/1205732265579288/1208839363050256/f)
When there is no query entered in the Search view, shows a list of recently visited stops.
iOS
android
Updated unit tests for affected views.

Jvc android search recent stops

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/more/MoreViewModelTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/MorePageTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetGlobalDataTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetRailRouteShapesTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetStopMapDataTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToAlertsTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToVehiclesTest.kt

_Ticket:_ [Fix flaky android emulator tests](https://app.asana.com/0/1205732265579288/1208937603891770/f)
I went through the 25 most recent CI failures, ignored the ones where other CI steps failed or the failing emulator tests looked related to the changes made in the PR, and added a `waitUntil` to give the non-Compose mocked network requests a little more time to settle. (I also added some scrolling on the one test here that was failing in Compose assertions, on the assumption that it's a scrolling issue again.)
iOS
android
- ~~[ ] Expensive calculations are run …

fix(Android): make flakiest tests more robust

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToPredictionsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/StopDetailsPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/phoenix/PhoenixSocketWrapper.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToPredictions.kt

_Ticket:_ [🤖 | Nearby | Reset state when panning or recentering](https://app.asana.com/0/1205732265579288/1208915825996354/f)
I thought this would be easy, and if I knew one more thing about ViewModels it would've been easy, but I did not, so this was really difficult.
iOS
android
Manually verified that the ViewModel gets reset and the stale data does not flash in for a frame or two.

fix(Android): reset nearby transit state on pan/recenter

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetGlobalDataTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetScheduleTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToPredictionsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/StopDetailsPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlay.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getGlobalData.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getSchedule.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToPredictions.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/ErrorBannerStateRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/GlobalRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SchedulesRepository.kt

_Ticket:_ [🤖 | Unfiltered Stop Details | Display error banners](https://app.asana.com/0/1205732265579288/1208968297244759/f)
Solves part 2 of https://github.com/mbta/mobile_app/pull/638. 
`getSchedule` was always using the same errorKey, so a race condition where the nearby transit `getSchedule` request finishes after the `stopDetails` request resulted the stopDetails error banner disappearing.
Now, getSchedule and getGlobalData take an errorKey param so the error can be recorded in a context-dependent way.
Additionally, while debugging I noticed that checkPredictionsStale was not being called periodically. This adds that functionality.
_Note:_
I created a[ separate ticket](https://app.asana.com/0/1208621177839510/1209118361132271/f) to appropriately clear the error …

fix(StopDetailsPage): Distinct errorKeys from API requests on NearbyTransitPage

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/Analytics/DestinationRowAnalytics.swift
iosApp/iosApp/Analytics/NearbyTransitAnalytics.swift
iosApp/iosApp/Analytics/StopDetailsAnalytics.swift
iosApp/iosApp/Pages/LegacyStopDetails/StopDetailsFilteredRouteView.swift
iosApp/iosApp/Pages/LegacyStopDetails/StopDetailsRouteView.swift
iosApp/iosApp/Pages/NearbyTransit/DestinationRowView.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyStopView.swift
iosApp/iosApp/Pages/NearbyTransit/StopDeparturesSummaryList.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift

_Ticket:_ [GA Updates](https://app.asana.com/0/1205732265579288/1209010745257736/f)
This piece wound up being architecturally nontrivial on its own, so I'm breaking it out into its own PR for more targeted review.
iOS
android
Manually verified with `debugPrint` that the right data would be sent to GA if analytics events were sent in debug mode. (No automated tests because that's [a separate task](https://app.asana.com/0/1208621177839510/1207938446689320/f).)

feat(analytics): log mode and no_trips in tapped_departure

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/ViewModels/SettingsViewModel.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepositoryTest.kt

_Ticket:_ [Elevator Status | Feature flag](https://app.asana.com/0/1205732265579288/1209143579111803/f)
Adds a new feature toggle for elevator status (to be later moved into settings).
iOS
android
N/A

feat: Add elevator accessibility feature toggle

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/MainApplication.kt
iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ContentView.swift
iosApp/iosApp/ProductionAppView.swift
iosApp/iosApp/Utils/CurrentAppVersionRepository.swift
iosApp/iosApp/ViewModels/ContentViewModel.swift
iosApp/iosAppTests/Views/ContentViewModelTests.swift
shared/src/androidMain/kotlin/com/mbta/tid/mbta_app/model/FeaturePromo.android.kt
shared/src/androidMain/kotlin/com/mbta/tid/mbta_app/repositories/CurrentAppVersionRepository.android.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/AppModule.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/RepositoryDI.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/UsecaseDI.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/makeNativeModule.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/AppVersion.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/FeaturePromo.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/CurrentAppVersionRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/LastLaunchedAppVersionRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/usecases/FeaturePromoUseCase.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/AppVersionTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/usecases/FeaturePromoUsecaseTest.kt
shared/src/iosMain/kotlin/com/mbta/tid/mbta_app/model/FeaturePromo.ios.kt

_Ticket:_ [Set up logic for new feature promo](https://app.asana.com/0/1205732265579288/1209120993502865/f)
I am happy with this structure, which means I may have overengineered it.
iOS
android
Added some unit tests. Manually verified that the versions are being stored on both Android and iOS and therefore if we ship this in 1.1.5 we should be able to use it in 1.2.0.

feat: set up logic for new feature promotion

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ComponentViews/AlertCard.swift
iosApp/iosApp/ComponentViews/InfoIcon.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/LegacyStopDetails/StopDetailsAlertHeader.swift
iosApp/iosApp/Pages/LegacyStopDetails/StopDetailsDownstreamAlert.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredView.swift
iosApp/iosApp/Pages/StopDetails/TripHeaderCard.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsFilteredDepartureDetailsTests.swift
iosApp/iosAppTests/Views/AlertCardTests.swift

_Ticket:_ [ | Stop + Trip Details | Show disruption downstream](https://app.asana.com/0/1209140624048233/1209154953848789/f) + [ | Stop + Trip Details | Handle Service changes + unspecified stops](https://app.asana.com/0/1209140624048233/1209154953848791/f)
Combined the downstream and secondary alert tickets because it ended up being easier to just do them both at once.
Adds a spec to the AlertCard which can be `major`, `secondary`, or `downstream`.
iOS
Added unit tests for new behavior

feat(iOS): UI for secondary and downstream alerts in combined stop details

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/SheetRoutesTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModelTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/MainApplication.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/SheetRoutes.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitTabViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/StopDetailsPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getSchedule.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToPredictions.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/stopDetailsPage/StopData.kt

_Ticket:_ [🤖 | stop + trip details | barebones UX](https://app.asana.com/0/1205732265579288/1209118361132266/f)
This PR moves the data management of the `StopDetailsPage` out of the component and into a new `StopDetailsViewModel`. This will be helpful for organization going forward and is key to resolving an issue with https://github.com/mbta/mobile_app/pull/653, where changing a filter within the stop details page (like tapping a route pill) caused the whole page to reload.
Heavily referenced [StopDetailsViewModel.swift](https://github.com/mbta/mobile_app/blob/main/iosApp/iosApp/ViewModels/StopDetailsViewModel.swift), pulling in the minimum logic necessary to resolve this one particular issue and unblock other work. We can pull more into the view model as we go.
iOS …

refactor(StopDetailsPage): Pull data into VM

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredRouteViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsRoutesViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModelTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/MainApplication.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/LoadingStopDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredRouteView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsRoutesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsHeader.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStops.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/stopDetailsPage/TripData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/stopDetailsPage/TripHeaderSpec.kt

_Ticket:_ [🤖 | stop + trip details | barebones UX](https://app.asana.com/0/1205732265579288/1209118361132266/f)
This PR adds all functionality to the StopDetailsViewModel for fetching the relevant trip + vehicle data based on the trip filter.
Based entirely on [StopDetailsViewModel.swift](https://github.com/mbta/mobile_app/blob/main/iosApp/iosApp/ViewModels/StopDetailsViewModel.swift). I considered pulling out some common helper classes, but for expediency opted not to at this point since this PR is blocking other work.
iOS
android
* Added unit tests based on swift tests & updated existing tests
* Ran locally with logs & confirmed data loads as expected

feat(android.StopDetailsViewModel): Trip & vehicle data

---

iosApp/iosApp/Info.plist

chore(iOS): Bump version to 1.1.5

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModelTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt

Follow up to https://github.com/mbta/mobile_app/pull/675, which introduced some tests that are still flaky.
An attempt to resolve flakiness in the `stopDetailsManagedVM` tests. I expaned the use of the StandardTestDispatcher recommended [here](https://developer.android.com/kotlin/coroutines/test#standardtestdispatcher) to the view model in each managedVM test. These tests passed running repeatedly locally, except for `testManagerHandlesTripFilterChange` which consistently failed until I also added `composeTestRule.awaitIdle()` I'm not entirely sure why that test in particular was failing. 
If these continue to flake after these changes, then we should take @EmmaSimon's suggestion of skipping them for now and make a ticket to follow up on them.
iOS
android
What testing …

test(StopDetailsViewModel): Address remaining flakiness

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/onboarding/OnboardingScreenView.kt

_Ticket:_ No ticket, reported [on slack](https://mbta.slack.com/archives/C07HCGLKZPY/p1737734821511149)
Switches onboarding image scaling to crop rather than stretch to fill bounds, and fill max size rather than max width.
android
~- [ ] All user-facing strings added to strings resource~
N/A

fix(Android): Prevent squashed onboarding images

---

shared/src/androidMain/kotlin/com/mbta/tid/mbta_app/repositories/AccessibilityStatusRepository.android.kt

_Ticket:_ none
[Slack message](https://mbta.slack.com/archives/C05QMG9GS9M/p1738003892339439?thread_ts=1738001493.639229&cid=C05QMG9GS9M)
On Android, a lot of non-accessibility-related apps run as accessibility services to get access to info like which app is running. If I have two of those running, I should not see the hide maps onboarding screen.
iOS
android
Verified that on my personal phone neither [Tasker](https://tasker.joaoapps.com/) nor …

fix(Android): skip hide maps onboarding for non-accessibility accessibility services

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt

_Ticket:_ [🤖 | respond to first batch of QA feedback](https://app.asana.com/0/1205732265579288/1209263422629657/f)
[Per Slack](https://mbta.slack.com/archives/C05QMG9GS9M/p1738247231226519?thread_ts=1738190984.789789&cid=C05QMG9GS9M), not including the focus order and route pin button tweaks.
iOS
android
Manually verified that the Mapbox logo is no longer present in accessibility traversal but the Mapbox attribution button still is.

fix(Android): respond to TalkBack P0 QA

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCard.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStops.kt

_Ticket:_ [🤖 | stop + trip details | Trip details UI](https://app.asana.com/0/1205732265579288/1209118487744430/f)
This PR adds the basic UI for the trip details stop list. It does *not* include the "Stop X stops away" UI or the trip line, but wanted to break off this small chunk bit before the[ UI ticket for the Trip Header Card ](https://app.asana.com/0/1205732265579288/1209118480622202/f) is picked up since this touches that a bit too.
iOS
android
* Ran locally, getting closer to final UI

feat(android.TripDetails): Initial UI layout improvements

---

androidApp/build.gradle.kts
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/more/MoreViewModelTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt
iosApp/iosApp/ViewModels/SettingsViewModel.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/morePage/feedbackFormUrl.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/morePage/FeedbackFormUrlTest.kt

_Ticket:_ [Name](URL)
No ticket, [request on slack](https://mbta.slack.com/archives/C05QMG9GS9M/p1738340696065619) to change the feedback URL for the beta.
iOS
android
* Updated unit tests
* Ran locally & confirmed taken to the android form as expected
* Confirmed iOS link still goes to /appfeedback

feat(android.feedbackFormUrl): Separate android feedback form

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/AlertCardTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/AlertCard.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/AlertEffectExtension.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml

_Ticket:_ [🤖 | Stop + Trip Details | Show disruption downstream & handle service changes + unspecified stops](https://app.asana.com/0/1205732265579288/1209204160447281/f)
Add mini MVP card for downstream disruptions, service changes, and unspecified stops. 
iOS
android
~~- [ ] Expensive calculations are run in `withContext(Dispatchers.Default)` where possible~~
Added tests for the various states.

feat(Android): Downstream disruptions/service changes

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesView.kt

_Ticket:_ [🤖 | Stop + Trip Details | Show disruption here](https://app.asana.com/0/1205732265579288/1208851006555187)
Added changes to omit departures and trip info when there's a major alert. Also added suggested tests from #696
iOS
android
~~- [ ] All user-facing strings added to strings resource in alphabetical order~~
~~- [ ] Expensive calculations are run in `withContext(Dispatchers.Default)` where possible~~
Added automated tests for disruption cases.

feat(Android): show disruptions here

---

iosApp/ci_scripts/ci_post_clone.sh

_Ticket:_ none
Saw this in an iOS build failure. It's [documented](https://asdf-vm.com/guide/upgrading-to-v0-16.html#hyphenated-commands-have-been-removed) as an asdf 0.16 breaking change, although I don't understand why they couldn't just keep these as aliases.
iOS
android
I still have asdf 0.15 locally, so I'm just kinda assuming based on the docs that this will work.

fix: make iOS CI compatible with asdf 0.16

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsNoTripCardTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCardTest.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/Onboarding/OnboardingScreenView.swift
iosApp/iosApp/Pages/Promo/PromoPage.swift
iosApp/iosApp/Pages/Promo/PromoScreenView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsNoTripCard.swift
iosApp/iosApp/Pages/StopDetails/TripHeaderCard.swift
iosApp/iosApp/Utils/FullWidthButtonModifiers.swift
iosApp/iosAppTests/Pages/Promo/PromoPageTests.swift
iosApp/iosAppTests/Pages/Promo/PromoScreenViewTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsNoTripCardTests.swift
iosApp/iosAppTests/Pages/StopDetails/TripHeaderCardTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/FeaturePromo.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/usecases/FeaturePromoUsecaseTest.kt

_Ticket:_ [ | Combined Stop + Trip Details: Launch promo](https://app.asana.com/0/1205732265579288/1209309195022071)
Adds the UX for the combined stop + trip promo page. We don't have a finalized graphic yet, so that's left as a todo, and it's only set to show up once we update the version number to 1.2.0, so currently you can only make it show up by manually updating the version locally.
iOS
Added some basic UI tests

feat(iOS): Combined stop + trip promo UX

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/HomeMapViewTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCardTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/RecenterButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreLink.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MorePhone.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/Map/RecenterButton.swift
iosApp/iosApp/Pages/More/MorePhone.swift
iosApp/iosApp/Pages/StopDetails/TripHeaderCard.swift
iosApp/iosAppTests/Pages/StopDetails/TripHeaderCardTests.swift

_Ticket:_ [[send out another batch of translations]](https://app.asana.com/0/1205732265579288/1209230846082285)
This updates a final few localizable strings on across both Android and iOS, it adds a few to the iOS source of truth that only exist on Android, and updated a few on both platforms which were identified during QA.
iOS
android
Updated tests that rely on the updated translations, verified that updated screen reader behavior is as expected

i18n: Translation pass before sending to vendor

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/more/MoreViewModelTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/MapViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/phoenix/PhoenixSocketWrapper.kt

_Ticket:_ [🤖 Re-profile app to identify performance issues](https://app.asana.com/0/1205732265579288/1209264000440745)
It might make sense to move these to a background thread inherently, but I don't want to make the iOS changes that that'd imply right now.
iOS
android
Manually verified that the map still looks reasonable and these functions appear in the profile on background threads.

fix(Android): performance low-hanging fruit

---

.tool-versions
androidApp/src/main/java/com/mbta/tid/mbta_app/android/MainActivity.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreLink.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MorePhone.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreSectionView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/morePage/MoreItem.kt

_Ticket:_ [🤖 | Sentry | Fix integration again](https://app.asana.com/0/1205732265579288/1209295122854608)
This is step towards investigating the sentry issues, I was able to get logs showing up from a local dev build, but builds created through the workflow don't seem to be working. This adds a button to the more page in staging which crashes the app and also explicitly logs a message to Sentry. My guess is that the issue is somewhere in the env vars being set in the workflows.
android
Manually tested locally

fix(Android): Add crash button

---

.github/workflows/android-deploy.yaml
.github/workflows/ci.yaml
androidApp/src/main/java/com/mbta/tid/mbta_app/android/MainActivity.kt

_Ticket:_ [🤖 | Sentry | Fix integration again](https://app.asana.com/0/1205732265579288/1209295122854608)
Set sentry env vars in workflow build step. Also don't require the sentry environment to be set in the app, and fall back to "debug" if none is defined.
iOS
android
Can't test build steps locally

fix(Android): Set sentry env vars in workflow

---

androidApp/src/main/AndroidManifest.xml

At the moment, the app doesn't support any languages that are written from right to left, such as Hebrew or Arabic.
However, AndroidManifest.xml says android:supportsRtl="true", which is the default value. This causes the app to display incorrectly in English on phones that are set to work in a right to left language.
This patch sets rtlandroid:supportsRtl="false",
so that the app won't try to flip itself for
right to left languages unnecessarily.
If full support for such languages is ever added,
set it back to "true".

Disable RTL support

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt

_Ticket:_ none
[Slack message](https://mbta.slack.com/archives/C05QMG9GS9M/p1739462362128799?thread_ts=1739457500.701929&cid=C05QMG9GS9M)
I should have checked this in #724.
|Before|After|
|------|-----|
|<img width="439" alt="Screenshot 2025-02-13 at 11 25 07 AM" src="https://github.com/user-attachments/assets/187830a8-99bf-4499-b310-f8473785aec0" />|<img width="443" alt="Screenshot 2025-02-13 at 11 24 37 AM" src="https://github.com/user-attachments/assets/6efccbdc-0b7e-42a7-9e94-4bcf362fb41e" />|
iOS
android
Checked in the Android Studio preview that the fix works.

fix(Android): correct color for CR status in deselected tile

---

androidApp/src/main/AndroidManifest.xml
androidApp/src/main/java/com/mbta/tid/mbta_app/android/MainActivity.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlay.kt

_Ticket:_ [Android | Map extends to top of screen](https://app.asana.com/0/1205732265579288/1209343093134602)
Removes the black bar behind the top system icons and extends the map to cover the whole screen.
iOS
android

enable edge-to-edge map coverage of the screen

---

androidApp/build.gradle.kts
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlayTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/results/StopResultsViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetSearchResultTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/MainApplication.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/RoutePill.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlay.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/StopResultsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getSearchResults.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings

_Ticket:_ [🤖 | non-P0 QA findings](https://app.asana.com/0/1205732265579288/1209343093134597)
This PR includes a few minor fixes to search and the map
* Search bar padding & border fixes
* I was not able to modify the search bar height with a reasonable amount of trying.
* Search result station pills order, groups bus & CR pills 
* Search bug fix: Recently viewed no longer missing on first open
* Map pulsing location, attribution alignment
iOS
android
* Ran locally

fix(android.search,map): Style updates

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitTabViewModelTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitTabViewModel.kt

_Ticket:_ [🤖 | Fix: Tapping direction toggle adds to nav stack](https://app.asana.com/0/1205732265579288/1209433346935160)
Don't add new navigation items to the stack when the direction toggle is tapped in the same direction that's already selected.
android
Manual testing

fix(Android): Fix direction toggle nav bug

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/TestUtils.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/alertDetails/AlertDetailsTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRowTest.kt

_Ticket:_ none
I think it's Android 14 (API 34) that introduced this change, but it's hard to tell.
iOS
android
Ran the tests on a recent API level AVD and confirmed that they now pass instead of failing.

fix(Android): handle NNBSP in 12-hour times when testing on recent API levels

---

androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
buildSrc/src/main/kotlin/com/mbta/tid/mbta_app/gradle/ConvertIosLocalizationTask.kt

_Ticket:_ none
This is a weird corner of the conversion script; if we planned to be adding new languages on a regular basis, it'd be worth trying to detect this issue in the script and give a more useful warning, but we do not.
iOS
android
Verified that the in-tree data now matches the script output and does not cause the lint message about missing cases.

fix(Android): add French to list of languages with decimal plurals

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/HomeMapViewTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlayTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/location/ViewportProvider.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/TripCenterButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlay.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getSearchResults.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/MapboxUtil.kt

_Ticket:_ [🤖 | stop + trip details | Recenter on vehicle button](https://app.asana.com/0/1205732265579288/1209118824865491)
Adds the button to show the overview of your selected vehicle/trip
iOS
android
Automated testing for reproducible map states, manual testing for the states we can't currently create in the test environment (going off existing test coverage).

Android recenter on vehicle

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt

No ticket. Removes the sentry test crash button now that we know Sentry is properly configured. Something that is crawling the staging app keeps hitting this button and causing [noise in our alerts channel](https://mbta.slack.com/archives/C08242XU3RR/p1739289614762199).
iOS
android
* Ran locally, confirmed no crash button

feat(android.MorePage): Remove debug sentry crash button

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/HomeMapViewTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/location/ViewportProvider.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/PaddingArithmetic.kt

_Ticket:_ [🤖 | Fix partial black map issues](https://app.asana.com/0/1205732265579288/1209367654923213)
This was easy until I ran the tests.
iOS
android
Manually verified that the map peeks out from under the corners of the sheet, that the Mapbox logo and attribution are visible when the map is visible, and that the logical center is properly maintained in all map states.

fix(Android): draw map under sheet regardless of sheet state

---

iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/AlertDetails/AlertDetails.swift
iosApp/iosApp/Pages/Onboarding/OnboardingScreenView.swift
iosApp/iosApp/Pages/Promo/PromoScreenView.swift
iosApp/iosApp/Utils/Typography.swift

_Ticket:_ [iOS | Onboarding punch list](https://app.asana.com/0/1201654106676769/1209433125172607)
I forgot that we would be able to use the same name for the typography extension method; that simplifies things a lot. It's weird that the way SwiftUI handles line height is so inflexible.
iOS
android
Checked in previews and in the live app that things look more correct now than they did previously.

fix(iOS): work through onboarding punchlist

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/Crosshairs.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt

_Ticket:_ none
I forgot to check this in #765; the crosshair currently draws at the center of the full map regardless of how much of the map is behind the sheet, which is incorrect and not helpful.
iOS
android

fix(Android): give sheet padding to map crosshair while panning

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/PredictionRowView.kt

_Ticket:_ [🤖 | Fix Added trip crash ](https://app.asana.com/0/1205732265579288/1209465916321745)
There was a crash report for when there was a prediction for an added trip that wasn't yet present in the trip map. 
For consistency with the [iOS PredictionRowView](https://github.com/mbta/mobile_app/blob/e261a263e0d7e4cfefcad026d9e4ee25c0a6f754/iosApp/iosApp/ComponentViews/PredictionRowView.swift#L90), the RoutePill is only rendered if there is a route present in `routesByTrip`.
iOS
android
* Ran locally with the route forced to null, confirmed that GL predictions still render without the pill.

fix(android.PredictionRowView): Don't crash if missing trip from map

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/TightWrapText.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCard.kt

_Ticket:_ [🤖 | Fix scheduled to depart info icon](https://app.asana.com/0/1205732265579288/1209465916321750)
Workaround for an annoying and old [Android bug](https://issuetracker.google.com/issues/206039942).
android
Tested layout at different text sizes.

fix(Android): Info icon layout

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/ViewportSnapshot.kt

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1740173937802989)
Re-applying the insets when we restore might've worked too.
iOS
android
Verified that the bug Paul recorded doesn't happen anymore.

fix(Android): only persist zoom and center, not edge insets

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyStopView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRow.kt

No ticket, from [slack convo](https://mbta.slack.com/archives/C05QMG9GS9M/p1740174183461249). 
Adjusts some weights so that long text doesn't take up too much space in rows. Probably will play a bit more with the stopped X stops away weighting so it isn't cut off so badly
iOS
android

fix(android.weights): Adjust weights for elevator alert, stopped X stops away

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/location/MockLocationDataManager.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/HomeMapViewTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt

No ticket
Show the recenter on current location button in stop details.
iOS
android

fix(Android): show recenter button on stop details

---

.github/actions/setup/action.yml
.github/workflows/android-deploy.yaml
.github/workflows/android-staging-deploy.yaml
.github/workflows/ci.yaml

_Ticket:_ [Move iOS CI/CD to GitHub Actions](https://app.asana.com/0/1205732265579288/1209226816339255)
If we regularly need the same tools for the same reasons, it's more legible if we separate the reasons from the tools themselves. This is a change I had in #555 that seems worth splitting out into a standalone refactor.
I also realized that the AWS and Android code signing setup would make sense to have as part of this action. Hopefully that all works, because it'll be difficult to test from this branch.
iOS
android
- ~~[ ] Expensive …

refactor: add some indirection to setup action

---

.github/actions/setup/action.yml
.github/workflows/ci.yaml
.gitignore
fastlane/Fastfile
fastlane/README.md
shared/build.gradle.kts

_Ticket:_ [Move iOS CI/CD to GitHub Actions](https://app.asana.com/0/1205732265579288/1209226816339255)
I think this piece works and could be merged as-is to replace our PR CI workflow in Xcode Cloud. It's been a while, though; it might not still work. Also, there's risk of drift between our GitHub Actions CI for PRs and our Xcode Cloud CD for staging and production deploys, and if something works from GitHub Actions but fails from Xcode Cloud then our misery will be ceaseless, so it might make sense to leave the Xcode Cloud CI running until we get deployments from GitHub Actions working properly.
iOS
android
- ~~[ ] All …

ci: run iOS tests in GitHub Actions

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Prediction.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Schedule.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripStopTime.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplayTest.kt

_Ticket:_ [Show BRD even if prediction is in past](https://app.asana.com/0/1205732265579288/1209072793746974)
There are a lot of cases that we want to not change here, so I think this has made `TripInstantDisplay.from` more complicated. Perhaps it'd be worthwhile to have more explicitly diverging code paths per route type at some point.
iOS
android
Added unit test for new case.

fix: keep showing BRD if vehicle is still present after prediction elapses

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/location/ViewportProvider.kt

_Ticket:_ [Fix: stop details map buttons ](https://app.asana.com/0/1205732265579288/1209485723122809)
Fixes an issue where both recenter and trip center buttons would disappear when toggling between them. Also adds a 20px padding for when the selected vehicle is in the top right of the screen.
iOS
android
Manual, unfortunately hard to test map interactions currently

fix button toggling and add some extra padding around vehicle overview viewport

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredRoutesViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModelTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosApp/ViewModels/SettingsViewModel.swift
iosApp/iosApp/ViewModels/StopDetailsViewModel.swift
iosApp/iosAppTests/ViewModels/StopDetailsViewModelTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDepartures.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/NearbyResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RealtimePatternsTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/StopDetailsDeparturesTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TemporaryTerminalTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepositoryTest.kt

_Ticket:_ [Group by direction | Feature flags](https://app.asana.com/0/1205732265579288/1209536961544694)
Removes old TripHeadsigns feature flag & adds a new GroupByDirection flag. This leaves the old TripHeadsigns functions in place so that we can easily reference them while building up the group by direction functionality, but removes all entry points from the UI to those functions so that we can freely break them as needed.
Also removes the now unused `CombinedStopAndTrip` feature flag.
iOS
android
* Ran iOS application, android application, confirmed both run.

feat: remove old TripHeadsigns feature flag & add new GroupByDirection flag

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/location/ViewportProvider.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/MapViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt

_Ticket:_ [Fix: Android location issues](https://app.asana.com/0/1205732265579288/1209485724244302)
This PR fixes the issue in the second bullet of the linked ticket. The issue in the first bullet did not reproduce, but [Paul found another bug with the recenter button](https://mbta.slack.com/archives/C05QMG9GS9M/p1740672500855899?thread_ts=1740672061.625109&cid=C05QMG9GS9M) which this PR corrects.
iOS
android
Manual testing since we don't have a good way of testing location behavior

Android location issues

---

.github/workflows/build-android.yaml

_Ticket:_ none
I missed a couple of spots when tweaking #807 to convert inputs to lowercase itself rather than requiring both cases as separate inputs.
This sort of thing is why I don't actually like GitHub Actions. A real programming language would have functionality like "convert this string to lowercase" and "error early if referencing an input that doesn't exist".
iOS
android
Not testable.

fix(ci): correctly reference lowercase values when uploading artifacts

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt

_Ticket:_ [Set min/max map zoom for Android](https://app.asana.com/0/1205732265579288/1209538649680545)
We've had this on iOS, but forgot to ever include it on Android
android
Manually tested to make sure it was bounded

fix(Android): Add map zoom bounds

---

iosApp/iosApp/ContentView.swift
iosApp/iosApp/Pages/Map/AnnotatedMap.swift
iosApp/iosApp/Pages/Map/RecenterButton.swift
iosApp/iosApp/Pages/Search/Results/SearchResultsView.swift
iosApp/iosApp/Pages/Search/SearchField.swift
iosApp/iosApp/Pages/Search/SearchOverlay.swift
iosApp/iosApp/Utils/PresentationDetentExtension.swift

_Ticket:_ [iOS | Map extends to top of screen](https://app.asana.com/0/1205732265579288/1207426150145420)
This required a bit of extra padding and background color fiddling to get everything working properly, especially with the search overlay (initially it was still showing a slice of the map above the open search bar).
iOS
Manual testing that everything looked reasonable with hide maps turned on and off.

feat(iOS): Draw map behind top bar safe area

---

.github/actions/setup/action.yml
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Utils/SelectedTab.swift
iosApp/iosAppTests/Pages/StopDetails/DepartureTileTests.swift
iosApp/iosAppTests/Pages/StopDetails/ExplainerPageTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
iosApp/iosAppTests/Pages/StopDetails/TripHeaderCardTests.swift
iosApp/iosAppTests/Views/NearbyTransitViewTests.swift
iosApp/iosAppTests/Views/UpcomingTripViewTests.swift
iosApp/iosAppUITests/EndToEndOpenStopDetailsTest.swift

_Ticket:_ [Build with Xcode 16](https://app.asana.com/0/1205732265579288/1209498488512445)
Upgrade the iOS build SDK to 18 by upgrading the XCode version CI uses to 16.2.
This builds fine for iOS 18 devices and all tests pass running locally on 16.2.
iOS
All tests broken by XCode 16 behavior have been fixed

chore(iOS): Switch to XCode 16 and iOS 18 SDK

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RealtimePatterns.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RoutePattern.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [Group by direction | Foundational data structure](https://app.asana.com/0/1205732265579288/1209536961544699)
This PR adds upcoming trips to the RouteCardData structure and filters using the same rules as `NearbyStaticData.withRealtimeInfo` (filter cancellations, non-typical w/out upcoming trips, arrival only).
There are a few minor adjustments to this logic based on filtering by direction, I'll add specific comments where that is the case.
Still remaining work:
* Adding directions
* Sorting
* Adding equivalent of `hasSchedulesToday` (thinking of punting this entirely to the special service states ticket to unblock the barebones UX work)
iOS
android
* Ported tests of `NearbyStaticData.withRealtimeInfo` from `NearbyResponseTests` …

feat(RouteCardData): Add upcoming trips & filter

---

README.md
bin/csv-to-xliff.py

Suggested by @KaylaBrady [in slack](https://mbta.slack.com/archives/C062QNAJZ2M/p1742305579703879?thread_ts=1740087962.958649&cid=C062QNAJZ2M), I also added more general i18n docs to the readme, and updated the script to accept an input file path and output directory, rather than just using hardcoded values.

i18n: Add docs and CSV conversion script

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/cache/ResponseCache.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/GlobalRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/RailRouteShapeRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/cache/ResponseCacheTest.kt

_Ticket:_ [Fix stale parsed cache data](https://app.asana.com/0/1205732265579288/1209717539725073/f)
Fixes a couple related issues with the cache, the first was that all data was being parsed into the cache object type before being written to disk, which means that any data which existed in the response but was not included in the object would be erased, while leaving the etag the same, which resulted in the missing fields never being reloaded even if they were added to the object type. Now we write the response body directly to the disk cache without parsing it into an object first (though a parse does still happen prior to the write, so if the parse fails, nothing will be written).
Then, even with that fixed, we needed a way for the client to know that it was possible for the current …

fix: Make the cache not erase unknown backend fields

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripStopTime.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplayTest.kt

_Ticket:_ [BRD bug when train dwelling at station](https://app.asana.com/0/1205732265579288/1209702051776246/f)
When a train is dwelling at a station, show it as BRD to match in-station countown clocks. 
Similarly, if we predict that a train is already be at a station (but it doesn't have the StoppedAt boarding status), show ARR, even if departure is predicted more than 30 seconds out.
**Note:** This PR description suggested considering whether to refactor out `TripInstantDisplay.from` in conjunction with this change. I considered it but ultimately this change was so simple I don't think it is necessary to tie it to this change. After thinking more about how I would approach that refactor, I'm also not totally sure we'd want to strictly split up this logic by mode, as …

fix(TripInstantDisplay): BRD / ARR when predicted arrival in the past

---

.pre-commit-config.yaml
fastlane/Fastfile

_Ticket:_ none
The first scheduled iOS dev-orange deploy [failed](https://github.com/mbta/mobile_app/actions/runs/14176894183/job/39713864460) because this setting defaults to three seconds. It’s not clear to me what the point of the timeout is if the advice is to just raise it if you ever actually hit it, but whatever.
I also noticed that the double quotes hadn’t been rewritten to single quotes by rubocop, which looks like it’s because pre-commit doesn’t know that Fastfile is a Ruby file.
iOS
android
Checked that the pre-commit hooks run, at least; this is a random failure that’s going to be hard to be certain we’ve addressed.

build: let Fastlane take longer to check xcodebuild settings

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/AlertAssociatedStop.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteSegment.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/AlertAssociatedStopTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteSegmentTest.kt

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1743608455909699)
I thought about hoisting the child stops’ `relevantAlerts` to the parent and removing the `childStops` field from `AlertAssociatedStop` completely, but I wasn’t confident it‘d be safe and I wanted to have something in place for this promptly.
iOS
android
Manually verified that the current Mattapan shuttle is correctly drawn on both iOS …

fix: dash routes for full-route alerts

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/MapHttpInterceptorTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/MapViewModelTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/more/MoreViewModelTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/MorePageTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlayTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/results/StopResultsViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetGlobalDataTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetRailRouteShapesTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetScheduleTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetSearchResultTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetStopMapDataTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToAlertsTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToPredictionsTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModelTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCardTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/util/ManagePinnedRoutesTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt

_Ticket:_ [[flaky android tests again]](https://app.asana.com/0/1205732265579288/1209645505139426/f)
I’m choosing to blame the StopDetailsViewModelTest failures on runTest - runTest is [suggested in the Android docs](https://developer.android.com/kotlin/coroutines/test), but not in a UI test context, and since we have access to `composeTestRule.waitForIdle()` instead, I think it’s a more realistic test if we don’t mess with the dispatchers at all. I’ve banished `runTest` throughout the tests so we never run into this issue again.
The MorePageTests failures don’t make a ton of sense to me, and I was having trouble reproducing them, so I’m just tossing in an extra `waitForIdle` and hoping that’s enough.
iOS
- ~~[ ] If you added any user-facing strings on iOS, are they included in …

test(Android): fix some flaky tests, hopefully

---

iosApp/iosApp/ComponentViews/TransitHeader.swift
iosApp/iosApp/Pages/More/MorePhone.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyStopView.swift
iosApp/iosApp/Utils/ViewModifier.swift

_Ticket:_ [Fix: VoiceOver bugs from research session](https://app.asana.com/0/1205732265579288/1209584641001346/f)
Makes the full width available to these text fields tappable to focus them.
iOS
android
Manually verified that the full available width is now tappable.

fix(iOS): widen focus area for stop and route names in nearby transit

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/HeadsignRowView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/NavDrilldownRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/PredictionRowView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/legacyRouteCard/StopDeparturesSummaryList.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/Departures.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCard.kt

_Ticket:_ [Group by direction | 🤖 Polish UI](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209536961544716?focus=true)
Samples selected from the [Figma spec](https://www.figma.com/design/eFiLM8xjo9hKprg93BBCtZ/App-UI-Design?node-id=9211-340210&t=Jps9NJcHKfDpav9h-4):
|Before|After|
|------|-----|
|<img width="354" alt="Screenshot 2025-04-10 at 10 21 48 AM" src="https://github.com/user-attachments/assets/f1522b34-0e8b-40eb-8a11-dfb716fd1cd4" />|<img width="354" alt="Screenshot 2025-04-10 at 10 23 08 AM" src="https://github.com/user-attachments/assets/3a5887ec-db4b-4ceb-bd6a-bb3851dacd3e" />|
|<img width="354" alt="Screenshot 2025-04-10 at 10 22 01 AM" src="https://github.com/user-attachments/assets/3c1300ea-1e6e-489c-b44b-b956de9d7d10" />|<img width="354" …

fix(Android): group by direction UI polish

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt

_Ticket:_ [🤖 bug: selected stop not centered on map](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209845006714026?focus=true)
It feels silly that this was the fix but here it is! Since we were attempting to position the viewport and simultaneously update map layers there seemed to be somewhat of a race condition happening that would cause the map to cease centering the viewport on the stop. Calling the suspending `refreshStopFeatures` first makes sure everything takes place before attempting to position the viewport.
iOS
android
~~- [ ] All user-facing strings added to strings resource in …

fix(Android): center stop on map

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStops.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
bin/filter-xcodeproj-diff.rb
iosApp/iosApp/Pages/StopDetails/TripStops.swift
iosApp/iosApp/Utils/KotlinIntExtension.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopListTest.kt

_Ticket:_ [Display downstream shuttles & suspensions in trip details](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209527076283977?focus=true)
Since we don’t know which alerts are downstream until we know what the target stop is, we can‘t truncate the stop list in `fromPieces`, only in `splitForTarget`. Since `splitForTarget` returns `null` to indicate that the target stop wasn’t found, it can’t do truncation in that case, which isn’t great; if it instead puts all the stops in the unconditionally-displayed `followingStops`, it will be able to truncate reasonably even if the target wasn’t found, and we don’t need a separate case.
I suggest reviewing with whitespace hidden.
iOS
- ~~[ ] If you added any user-facing strings on iOS, are they included in …

refactor: always return a TargetSplit from splitForTarget

---

.github/workflows/android-prod-deploy.yaml
.github/workflows/ios-prod-deploy.yaml

_Ticket:_ [Update CI to deploy both platforms when we use a certain tag format](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209633379255738?focus=true)
Adds new tag matching condition for ios + android to deploy to both platforms at once. 
Referenced this SO post and [GitHub Actions docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)
iOS
android
* Have not tested, but we can give it a try for our next release & I'll come back to edit as needed.

ci: run android/ios deploy when no platform prefix

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/PredictionRowView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/WithRealtimeIndicator.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCard.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/containsWrappableText.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/modifiers/DestinationPredictionBalance.kt

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1744994138263999?thread_ts=1744923529.120979&cid=C05QMG9GS9M)
Applies the destination and prediction sizing balance from #881/#885 to trip details, adds the padding called for in [the other Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1744983130060599) between the destination and prediction, and fixes the double applied transparency in trip details for disruption predictions.
iOS
android
- ~~[ ] Expensive calculations are run in …

fix(Android): more destination and prediction spacing tweaks

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt

_Ticket:_ [Android recenter button bug](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209802459425032?focus=true)
The user's current location was not being updated when the map wasn't visible, either because the sheet was expanded to max height, or the app was backgrounded. It was being caused by the nearby transit location being updated only by the camera state, which would stop sending updates when the map wasn't shown. 
This PR switches the nearby data to consume locations directly from the phone location stream, so that it doesn't matter what the map camera is doing. It also explicitly calls `follow` for the viewport every time the location updates, which prevents the map from getting stuck on an old location with no recenter button to reposition the map.
I'm …

fix(Android): Fix recentering to the current location

---

iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/Pages/StopDetails/TripStopRow.swift

_Ticket:_ none
The iOS version of the equivalent piece of #902.
iOS
android
Checked that disruptions and schedules are correctly faded out only once even in trip details.

fix(iOS): don’t double fade out schedules etc in trip details

---

.github/workflows/android-staging-deploy.yaml
.github/workflows/build-android.yaml
.github/workflows/build-ios.yaml

_Ticket:_ [Try out GitHub merge queue](https://app.asana.com/1/15492006741476/project/1205991273035889/task/1209644129662966?focus=true)
Merge queue is working pretty nicely, but we don’t need to run the tests again as part of staging deploys, and the concurrency protections were set up before merge queue and contained some assumptions that aren’t valid anymore.
iOS
android
Not tested.

ci: tweak a few things in response to merge queue

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/NavDrilldownRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredRoutesView.kt

_Ticket:_ [🤖 | Group by direction | Unfiltered stop details padding](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210024591221884?focus=true)
Fix padding on direction grouped unfiltered stop details, including for accessibility alerts. Also snuck in a fix for the clickable fill color not including the padding around the `NavDrilldownRow`.
android
Used screenshots to verify that these paddings match the spacing in direction grouped nearby transit.

fix(Android): Add padding to unfiltered stop details route cards

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsUnfilteredView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsView.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosApp/ViewModels/StopDetailsViewModel.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsUnfilteredViewTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsViewTests.swift

_Ticket:_ [Group by direction |  Unfiltered Stop Details UX](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209912113394461?focus=true)
The iOS version of #853.
iOS
android
Checked that grouping by direction works. Ported the Android unfiltered stop details tests to iOS including the old and the new behavior.

feat(iOS): group by direction in unfiltered stop details

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/TestUtils.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitPageTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/alertDetails/AlertDetailsPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToPredictions.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/Timer.kt
shared/src/androidMain/kotlin/com/mbta/tid/mbta_app/PlatformModule.kt

_Ticket:_ [Android recenter button bug](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209802459425032?focus=true)
Follow up to #908 
When the app goes to background, remember the timestamp, then the next time it comes back to the foreground, check how long ago it was backgrounded. If it was over an hour ago, clear the navigation stack, and follow the user's current location.
In order to test this, I needed to start injecting `Clock.System` with koin, this is recommended by the [kotlin docs](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-clock/-system/) to make usage of clocks more testable, but it required a bit of refactoring. 
I also switched the `timer` helper to return the state object rather than a single value, because I …

feat(Android): Reset nearby transit state after app has been backgrounded for over 1 hour

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt

…isruptions easier
_Ticket:_ [🤖 | Group By Direction | Disruption on a branch](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209979069137605?focus=true)
This splits out the `Leaf.format` fn into helper functions with clear split paths for branched route vs. non-branched route handing. This makes it easier to add logic specific to branched cases for disruptions / predictions unavailable in https://github.com/mbta/mobile_app/pull/918
iOS
android
* Pure refactor, confirmed all tests still pass

refactor(RouteCardData): Split out branching logic to support branching disruption cases

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCard.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [🤖 | Group By Direction | Disruption on a branch](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209979069137605?focus=true)
With this PR, we now show a separate row for disrupted branches when grouped by headsign to match designs.
Grouping by headsign when we know we are dealing with a branched route seemed like the most straightforward way to accomplish this. TY to @EmmaSimon for feedback on where that grouping logic should live! 
iOS
android
* Updated stubbed out unit tests 
* Updated android preview data & confirmed displayed as expected
* Tested in running app for a few alerts
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- …

feat(RouteCardData): Disruption on branch cases

---

iosApp/iosApp/ViewModels/NearbyViewModel.swift

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1745840910660239)
Fixes nearby transit resetting on location jitter.
iOS
android
Checked that it fixes location transitions that previously caused a reset.

fix(iOS): preserve nearby state while loading nearby stops

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCard.kt
iosApp/iosApp/ComponentViews/RouteCard/RouteCard.swift
iosApp/iosAppTests/Views/RouteCardTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/RouteCardPreviewData.kt

_Ticket:_ [Group by direction |  Handle branching vs non-branching](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209912113394443?focus=true)
Since it seemed as if branching/non-branching was already handled I decided to port the extensive previews Melody created for Android to iOS! This also helped me make sure I wasn't missing something. Instead of duplicating the test data in both code bases I moved it to a util in the shared library. Let me know if you have any thoughts on this.
iOS
android
~~- [ ] All user-facing strings added to strings resource in alphabetical order~~
~~- [ ] Expensive …

chore(iOS): add previews and disrupted branch test

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Alert.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/NearbyStaticData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [Group by Direction | Discard track changes at core stations](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210082542778227?focus=true)
We had a check in the `NearbyStaticData` to remove track change alerts from core CR stops (South and North St, Ruggles, Back Bay), which hadn't been included in the `RouteCardData` logic. This adds it.
iOS
android
Added new unit test verifying this behavior, manually …

fix: Discard track change alerts at core CR stops

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [Group by direction | Multiple nearby bus stops in the same direction](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210071791285856?focus=true)
This PR filters out stops from nearby transit that have upcoming trips that are completely redundant to earlier stops. 
Previously, we'd include a stop if it had any route pattern not seen by an earlier stop. Now, we include a stop if it has any route pattern not seen by an earlier stop that is typical or has upcoming service.
iOS
android
* Verified that for the GL case of Fenwood Road & Brigham Circle, Only Fenwood Road is shown. 
Before:
After:

fix(RouteCardData): Omit stops that have redundnant upcoming service

---

iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsUnfilteredView.swift

_Ticket:_ [Investigate: Scrolling Nearby Transit accidentally opens stop details](https://app.asana.com/1/15492006741476/project/1205425564113216/task/1210114954224733?focus=true)
This was annoying me and took like 5 mins to test
iOS
android
~~- [ ] All user-facing strings added to strings resource in alphabetical order~~
~~- [ ] Expensive calculations are run in `withContext(Dispatchers.Default)` where possible (ideally in shared code)~~
Manual

fix(iOS): Accidental taps while scrolling

---

.github/dependabot.yml

_Ticket:_ none
The default limit is [five](https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/working-with-dependabot/dependabot-options-reference#open-pull-requests-limit-), which we’re at right now. We don’t want to miss new updates just because we’ve got several that are either deliberately deferred or just not yet reviewed.
iOS
android
Not testable.

chore: increase Dependabot Gradle PR limit

---

gradle/libs.versions.toml
shared/build.gradle.kts
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/MapTestDataHelper.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/ObjectCollectionBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/ApiResult.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/GreenLineHelper.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/RouteCardPreviewData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/TestData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/map/RouteLayerGeneratorTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/map/StopFeaturesBuilderTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/map/StopLayerGeneratorTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/DirectionTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/Platform.jvm.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/ProjectUtils.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/model/Dependency.jvm.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/model/FeaturePromo.jvm.kt

_Ticket:_ [Make sets of test data for common scenarios for unit tests](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1206787308358329?focus=true)
I don’t know if I love this approach to generating the data, but I do think it would be more difficult to generate this subset from a Gradle task where we’re just tossing around the JSON directly.
I have not exhaustively checked for places where we could be using the new `TestData`.
iOS
android
- ~~[ ] Expensive calculations are run in `withContext(Dispatchers.Default)` where …

chore: generate test data from a subset of real data

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt

_Ticket:_ [Group by direction | Limit branching bus routes to two trips](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210130069642278?focus=true)
Only show 2 upcoming departures for branched bus routes instead of 3.
iOS
android
* Updated unit test
* Ran locally, confirmed showing 2 arrivals for route called out in the ticket

fix(RouteCardData): Only show 2 upcoming bus trips if branched

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/LoadingRouteCard.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredRoutesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsView.kt
iosApp/iosApp/ComponentViews/RouteCard/RouteCard.swift
iosApp/iosApp/ComponentViews/RouteCard/RouteCardDepartures.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsUnfilteredView.swift
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitViewLegacyTests.swift
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/LoadingPlaceholders.kt

_Ticket:_ [Group by Direction | Cleanup old nearby data codepaths](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210113865246640?focus=true)
Splitting this out as its own PR for easier review once it’s time to actually start deleting things.
iOS
android
Checked that the loading placeholder state looks like the loaded state structurally and spacing-wise.

feat: always use group by direction variants when loading

---

iosApp/iosApp/ComponentViews/SheetNavigationLink.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/DepartureTile.swift
iosApp/iosApp/Pages/StopDetails/DirectionPicker.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsUnfilteredView.swift

This seems to simultaneously fix Buttons aggressively capturing touch gestures and the ScrollView drag gestures being finnicky.
iOS
android
~~- [ ] All user-facing strings added to strings resource in alphabetical order~~
~~- [ ] Expensive calculations are run in `withContext(Dispatchers.Default)` where possible (ideally in shared code)~~
Manually tested on device.

fix(iOS): Fix finnicky scrolling on iOS

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingFormat.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/stopDetailsPage/TileData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/stopDetailsPage/TileDataTest.kt

_Ticket:_ [Handle cases where a trip stops at the same stop more than once](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210103117999218?focus=true)
This PR adds the stop sequence to the id used for `UpcomingTrip` and `TileData` so that the same arrival time doesn't appear twice for looped routes. 
This was not an issue for android with group by direction on, but was for iOS, presumably because of the requirements for a unique`id` when using `ForEach` in views on iOS. 
Note: The only other potentially affected id I found was for `LeafFormat` which is `"$headsign-$format-${Uuid.random()}"`, and therefore already unique.
iOS
android
* Updated unit test
* Ran locally on iOS & android, confirmed this is fixed in group …

fix(UpcomingTrip): Unique id to differentiate upcoming arrivals on looped routes

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/PatternSorting.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Stop.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [Group by direction | Rearrange sort precedence](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210130069642283?focus=true)
Don't sort routes to the bottom of nearby if only a single stop has service ended for the day. Also start sorting multiple stops in a route card based on distance and service ended status, along with service ended leaves.
iOS
android
Updated existing sort test to actually test …

fix: Update group by direction sort logic

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRow.kt
iosApp/iosApp/Pages/StopDetails/TripStopRow.swift
iosApp/iosAppTests/Pages/StopDetails/TripStopsTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Alert.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt

_Ticket:_ [Don't show downstream alerts for through service](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210161016755139?focus=true)
Stop displaying inline trip details alert cards on filtered stop details when the alert is not a shuttle or suspension.
iOS
android
Tested with dev alerts on DevOrange

fix: Don't show repetitive multi stop alert cards

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesView.kt
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/stopDetailsPage/TileData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/stopDetailsPage/TileDataTest.kt

_Ticket:_ [Selected trip is not highlighted on stop details](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210176112492141?focus=true)
This was introduced in #952, where upcoming trip IDs were made actually unique. This updates the departure tiles to check the UpcomingTrip's Trip id against the trip filter ID.
iOS
android
Verified that selected trips are highlighted again

fix: Check that the trip id matches, not tile id

---

iosApp/iosApp/ComponentViews/PredictionRowView.swift

_Ticket:_ [[Fix: vertical spacing for disruption messages / predictions unavailable]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210177544414517?focus=true)
The height of `PredictionRowView` was not taking up the desired minHeight in cases where the prediction text was less tall, like "Predictions unavailable" next to a "Shuttle Bus" alert row. I'm not certain why the inner minHeight wasn't being obeyed, but moving it up onto the HStack seems to have fixed the problem.
iOS
Verified that the height is properly set when "Predictions unavailable" is displayed on one line

fix(iOS): Fix PredictionRowView height

---

iosApp/iosApp/ContentView.swift

No ticket, quick fix based on[ slack discussion](https://mbta.slack.com/archives/C05QMG9GS9M/p1746631648361019)
iOS
android
* Ran locally and confirmed that the tab bar on the more page always has a background the first time I navigate to it. 
The bug seemed potentially device / OS related, so may require more testing to confirm if completely fixes the issue.

fix(ios.MorePage): Ensure tab bar always has background

---

iosApp/iosApp/ComponentViews/AlertCard.swift
iosApp/iosApp/ComponentViews/PinButton.swift
iosApp/iosApp/Pages/Map/AnnotatedMap.swift
iosApp/iosApp/Pages/StopDetails/DepartureTile.swift
iosApp/iosApp/Pages/StopDetails/TripDetailsDisclosureGroup.swift

_Ticket:_ [iOS | [Fix: tapping on stops on the filtered stop details map doesn't do anything]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210177544414522?focus=true)
In a kind of absurd turn of events, the `.simultaneousGesture(TapGesture())` modifier on the `DepartureTile` button was the thing that was, somehow, preventing taps on stops in the map from registering. This isn't actually a problem for the scrolling issue, because for some other arcane SwiftUI reason, scrolls that happen in horizontally scrolling containers don't seem to register as taps in the same way that scrolls in vertically scrolling containers do.
I also added a handful more `.simultaneousGesture(TapGesture())`s to a few other buttons I noticed could be triggered on scroll.
iOS
~- [ ] If you …

fix(iOS): Get stop details map stop taps working

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/location/LocationDataManager.kt
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/ProductionAppView.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitViewTests.swift

No ticket, addresses[ issue raised in slack](https://mbta.slack.com/archives/C05QMG9GS9M/p1745840910660239) where there have been some reports of nearby transit auto-scrolling to the top of the sheet when there are stops ~equidistant nearby. 
iOS
android
* added a unit test
* Tested locally with artificial location jitter at a coordinate known to be affected by this issue
* Tested in dev orange

fix(iosApp.NearbyTransitView): Don't reset nearby when stops reordered

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/routeCard/DeparturesTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCardTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/routeCard/StopHeaderTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitTabViewModelTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/Departures.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCard.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredRoutesView.kt
iosApp/iosApp/ComponentViews/RouteCard/RouteCard.swift
iosApp/iosApp/ComponentViews/RouteCard/RouteCardDepartures.swift
iosApp/iosApp/Pages/StopDetails/DirectionPicker.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredView.swift
iosApp/iosApp/Utils/LineOrRouteExtension.swift
iosApp/iosAppTests/Pages/StopDetails/DirectionPickerTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsFilteredDepartureDetailsTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsViewTests.swift
iosApp/iosAppTests/ViewModels/StopDetailsViewModelTests.swift
iosApp/iosAppTests/Views/HomeMapViewTests.swift
iosApp/iosAppTests/Views/RouteCardDeparturesTests.swift
iosApp/iosAppTests/Views/RouteCardStopHeaderTests.swift
iosApp/iosAppTests/Views/RouteCardTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/LoadingPlaceholders.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/RouteCardPreviewData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/PatternSortingTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [Group by Direction | Refactor RouteStopData and Leaf to include more context](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210114621155024?focus=true)
Not sure how easy the “If straightforward” section of the ticket will be, so may as well put the first half up as its own PR.
iOS
android
Updated unit tests. Checked that all tests pass.

refactor: put more RouteCardData context into RouteStopData

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt
iosApp/iosApp/ViewModels/SettingsViewModel.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepositoryTest.kt

_Ticket:_ [🤖 | Favorites | Feature flag](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209816289542463?focus=true)
Add a feature flag for upcoming favorites changes.
I opted not to add translations for the toggle label since it will only ever show up in staging.
iOS
android
Updated existing test

feat: Add Enhanced Favorites feature flag

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/DirectionPickerTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/StopListRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/RouteResultsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/DirectionPicker.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredPickerView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRow.kt
iosApp/iosApp/ComponentViews/DirectionLabel.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Direction.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [🤖 | Favorites | Route details - basic UX](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209816289542476?focus=true)
There are some refactoring pieces of this work that seem like they make sense to split out separately before the actual route details page implementation.
iOS
android
Checked that all tests still pass.

refactor: shared component and utilities in advance of route details

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/NearbyTransitPage.kt

_Ticket:_ [🤖 | Favorites | Add empty favorites tab](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209816289542468?focus=true)
Follow up to #979, this just splits out some of the logic from the former `NearbyTransitPage` which was renamed to `MapAndSheetPage` into a new `NearbyTransitPage` which exclusively handles nearby transit specific logic and renders the `NearbyTransitView`.
android
Existing tests pass

chore(Android): Refactor out nearby page logic

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetRouteStopsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/SheetRoutes.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getRouteStops.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/analytics/AnalyticsScreen.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/AppModule.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/RepositoryDI.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopList.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/RouteStopsResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/RouteStopsRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopListTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/RouteStopsRepositoryTest.kt

_Ticket:_ [🤖 | Favorites | Route details - basic UX](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209816289542476?focus=true)
Correctly handles selecting either a Green Line branch or the Green Line overall from route search, since that’s complicated in a way that influences the structure overall and I had an extra day within the task points.
iOS
android
Checked that this works with the Green Line and …

feat(Android): basic route details UX

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/HomeMapViewTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/location/ViewportProvider.kt

_Ticket:_ [🤖 | Current location not centered on app launch](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210226994170857?focus=true)
Ensures that on startup with location permissions enabled, the map defaults to your current location
* This seems to have  been caused by a change in Mapbox [11.12.0](https://github.com/mapbox/mapbox-maps-android/blob/main/CHANGELOG.md#11120-may-7-2025), but I can't quite pinpoint what from the changelog would do it. This was not an issue in 11.11.0
iOS
android
* Ran locally with permissions enabled and confirmed I am immediately brought to my current location
* Ran locally with permissions disabled and then enabled them. Confirmed I am brought to my current location

fix(android.HomeMapView): Default to current location if location permissions enabled

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCardTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRowTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCard.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStops.kt
iosApp/iosApp/Pages/StopDetails/TripDetailsView.swift
iosApp/iosApp/Pages/StopDetails/TripHeaderCard.swift
iosApp/iosApp/Pages/StopDetails/TripStopRow.swift
iosApp/iosApp/Pages/StopDetails/TripStops.swift
iosApp/iosAppTests/Pages/StopDetails/TripDetailsViewTests.swift
iosApp/iosAppTests/Pages/StopDetails/TripHeaderCardTests.swift
iosApp/iosAppTests/Pages/StopDetails/TripStopRowTests.swift
iosApp/iosAppTests/Pages/StopDetails/TripStopsTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/LoadingPlaceholders.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopListTest.kt

_Ticket:_ [Fix: display arrival time at shuttle boundary if possible to exit](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210239404411208?focus=true)
Whatever approach we wind up taking will involve refining the logic of how we decide whether to use the disruption or the formatted time, so it’ll be helpful to have one home for that logic rather than two.
iOS
android
Checked that all tests still pass.

refactor: move more logic into TripDetailsStopList.Entry.format

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsViewTest.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopListTest.kt

_Ticket:_ [Fix: display arrival time at shuttle boundary if possible to exit](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210239404411208?focus=true)
Easy after #986.
iOS
android
Checked that the disruption no longer displays instead of predictions for the current Orange Line shuttle.

fix: try to show time if exit not blocked by downstream alert

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/Departures.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesView.kt
iosApp/iosApp/ComponentViews/RouteCard/RouteCardDepartures.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt

_Ticket:_ [Fix: (Commuter Rail) delay alerts aren't filtered by trip](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210239404411192?focus=true)
I guess we just forgot to keep doing this in group by direction.
iOS
android
Checked that even if the alerts from the QA were all still active, only the one that applies to the selected trip would actually appear. Added a unit test.

fix: filter alerts by trip in filtered stop details

---

iosApp/iosApp/ComponentViews/HaloSeparator.swift
iosApp/iosApp/Pages/StopDetails/TripHeaderCard.swift
iosApp/iosApp/Pages/StopDetails/TripStopRow.swift
iosApp/iosApp/Pages/StopDetails/TripStops.swift

_Ticket:_ [iOS | Fix filtered stop details route line alignment](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210100739160856?focus=true)
Fixes route line alignment and targeted stop being too big
Manual

fix(iOS): route line alignment

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/MapAndSheetPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/MapAndSheetViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToPredictionsTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/ErrorBanner.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MorePage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredRoutesView.kt

_Ticket:_ No ticket, follow up to #973 (which this is merging into)
The `androidx.lifecycle:lifecycle-runtime-testing` 2.9.0 upgrade seems to include some updated Android linting which marks VMs instantiated inside a composable as an error. This moves all cases where this was happening (mostly in tests and previews) outside of the composable (or wrapped in a `viewModel`).
android
Tests pass

chore(Android): Move VM init out of composables

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [Group by Direction | GL direction labels not always working](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210318010176378?focus=true)
Destination labels in the direction toggle were blank on the trunk past Gov Ctr. This was happening because the atypical GL B and C patterns were included in the list sent to `Direction.getDirectionsForLine`, and would resolve to their branch destinations rather to the grouped destinations, and since they didn't match the grouped destination, none of them would be shown.
Checked that all branches and trunk stops on the GL show expected destinations, updated existing tests

fix: Only use typical patterns to determine direction toggle destinations

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt

_Ticket:_ [🤖 | Group By Direction | All trips are shown when navigating from unfiltered stop details](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210318500071981?focus=true)
Moving the route card state into the filtered view seems to have fixed the problem, I was initially trying to do something more complicated with filtering the flow based on context, but that was causing the loading state to flicker on every filter change.
Manually verified that extra trips no longer flash into unfiltered stop cards

fix: Prevent extra trips from appearing in unfiltered stop details when navigating to filtered

---

.github/workflows/ci.yaml

_Ticket:_ none
This piece of #993 appears to not have worked.
iOS
android
Can’t really be tested.

ci: fix filtering for skipping platform specific tests

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/DepartureTile.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesView.kt
iosApp/iosApp/Pages/StopDetails/DepartureTile.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift

_Ticket:_ [Set max width for departure tiles](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210239404411202?focus=true)
This PR ensures that long headsigns are wrapped in departure tiles so that they are more readable and it is more obvious you can scroll. 
This was easier on android than iOS, and I don't _love_ where I landed on iOS. The use of a `ScrollView` seems to affect how the ideal height of the tile is calculated, and I had a hard time getting the text to both wrap and be visible without this workaround. Please let me know if you have any other ideas / solutions here! Some discussed in [this thread](https://mbta.slack.com/archives/C062QNAJZ2M/p1747405439129889)
iOS
android
* Ran on iOS & android, confirmed …

feat(DepartureTile): Wrap long headsigns

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesView.kt
iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/stopDetailsPage/TileData.kt

_Ticket:_ [Fix VO focus when navigating to filtered stop details](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210322015597203?focus=true)
* Ensure we always focus on the first selected tile. This was a regression introduced by https://github.com/mbta/mobile_app/pull/952 when the id for an `UpcomingTrip` changed.
* Also includes android fixed discussed at dev check-in for resetting scroll position when changing direction
iOS
android
* Ran locally on iOS and confirmed that VO correctly focused on the first tile when coming from any view. 
* Thought about writing a ViewInspector test, but [accessibilityFocused](https://github.com/nalexn/ViewInspector/blob/0.10.2/readiness.md) is not yet implemented 
* Ran on android …

fix(ios.StopDetailsFilteredDepartureDetails): Preserve accessibility focus on tile

---

.github/workflows/ci.yaml

_Ticket:_ none
As can be seen in [this run](https://github.com/mbta/mobile_app/actions/runs/15145766015) of #1008, even now that the path filtering has been fixed in #1006, the conditions are broken. I am not sure if this will actually work, but if it does, then I will cry.
iOS
android
Can’t really be tested.

ci: really fix filtering for skipping platform specific tests

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt

_Ticket:_ [🤖 | GL pill flicker in stop details departure cards](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210329839893517?focus=true)
The GL pills on filtered stop details departure tiles were disappearing every time you changed the selected trip or direction toggle. This was happening because the global data was somehow being reset to null in `Leaf.format`, which was causing the route value to be null, even though a route ID existed and the route was meant to be displayed.
This PR moves the global data into a flow in the stop details VM. We store global in the map VM, so there was some precedence for this, and it ensures that we're always using the exact same global data in `stopDetailsManagedVM` that we are in the stop details pages.
android
~- [ ] All …

fix(Android): Prevent global data from being reset to null on every filter change

---

fastlane/Fastfile
fastlane/README.md

_Ticket:_ none
If the issue we ran into today comes back, this would probably fix it; the changes I made to the `sigh repair` command that actually worked were a little different and a little less straightforward to use, so I’m only mostly certain that this will work when we eventually need it to.
iOS
android
Checked that with nothing to do this doesn’t do anything. It is hard to fake a situation where this needs to do …

build(iOS): add a Fastlane lane for repairing provisioning profiles

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewModel.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt

_Ticket:_ [🤖 | Group By Direction | All trips are shown when navigating from unfiltered stop details](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210318500071981?focus=true)
This is a follow up to #1005, which didn't actually fix the problem. This is closer to the initial approach I was trying, but instead of using filtered flows entirely within the VM, I introduced flows that the `stopDetailsManagedVM` handles updating when the `routeId` or `routeCardData` change. This prevents the extra null init values, and allows us to remember the unfiltered route card data even after navigating into and back from a route filter, minimizing loading states.
android
~- [ ] Expensive calculations …

fix(Android): Move filtered/unfiltered state to VM

---

iosApp/iosApp/ComponentViews/RouteCard/RouteCardDirection.swift

_Ticket:_ [Group By Direction | Voice Control hints for route card](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210344414645468?focus=true)
This PR adds accessibilityInputLabels to the new RouteCard so that users can continue to say "Tap Alewife" or "Tap Braintree" to click into the row, rather than having to say "Tap Outbound" then select from all the visible outbound rows available. 
iOS
android
* Ran locally for both Voice Control & Voice Over. Confirmed that I could say "Tap [direction]", "Tap [destination]", or "Tap [headsign]". Looks like the OS has built-in shorthand for long headsigns, where you can just say "Tap [first word of headsign]". 
I'd definitely appreciate a second set of eyes & ears running this …

fix(ioS.RouteCardDirection): Accessibility input labels include headsigns

---

gradle/libs.versions.toml

_Ticket:_ none
Sometimes, Dependabot knows how to track down the changelog for dependencies it’s updating, and that’s nice. Other times, we need to hunt down the release notes ourselves, mostly in the Android standard library but sometimes on dependencies that just don’t have that working for whatever reason; for those, it seems like it’d be nice to have a link right there in the diff context, like we already do for the Jetpack Compose BOM.
iOS
android
- ~~[ ] Expensive calculations are run in `withContext(Dispatchers.Default)` where possible …

chore: add changelog links where dependabot doesn’t pull changelogs automatically

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt

_Ticket:_ [Group By Direction | Stop headsign disruption bug](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210356582922104?focus=true)
This PR resolves a suspension at a stop with multiple route patterns and stop headsigns would incorrectly still show upcoming service.
The cause was that we were using stop headsign to look up matching route patterns in `dataByHeadsign`, but there were no matches, and therefore no matching alerts.
iOS
android
* Ran locally and confirmed that for the current ferry disruption, we correctly show a single suspension row for Quincy Loop. 
* Confirmed other stops w/ stop headsigns still render as expected, like CR at south station
Before & After

fix(RouteCardData): Suspension at stop with stop headsigns

---

androidApp/build.gradle.kts
iosApp/iosApp/Info.plist

_Ticket:_ none
🎉 
Checked that this is all the places `1.2.2` shows up in the existing code.

chore: bump version number to 1.2.4

---

iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitViewTests.swift

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1748022822010349), issue 3
#921 treats `nil` and `[]` as equivalent stop lists and skips prediction loading if the stop list loads as empty, meaning the predictions were never loading as empty outside the service area.
iOS
android
Checked that this works. Added a test that would’ve caught this issue to ensure that this doesn’t break in this exact way …

fix(iOS): load empty predictions on empty stop list

---

androidApp/src/devOrange/AndroidManifest.xml
androidApp/src/main/java/com/mbta/tid/mbta_app/android/MainActivity.kt
androidApp/src/prod/AndroidManifest.xml
androidApp/src/staging/AndroidManifest.xml
iosApp/iosApp/IOSApp.swift
iosApp/iosApp/iosApp-dev-orange.entitlements
iosApp/iosApp/iosApp-prod.entitlements
iosApp/iosApp/iosApp-staging.entitlements
iosApp/project.yml

_Ticket:_ [Create link that opens the app if you have it installed and the store otherwise](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209949928014406?focus=true)
Sets up `/` as a deep link to open the app with no particular route.
Should work in the backend environments that https://github.com/mbta/mobile_app_backend/pull/318 is running in.
iOS
android
Checked that the iOS and Android versions should …

feat: set up deep linking

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/MapAndSheetPageTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/FavoriteConfirmationDialog.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings

_Ticket:_ [🤖 | Favorites | Stop details confirmation pop-up](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209816289572789?focus=true)
Styles & localizes the favorites confirmation dialog. 
Confirmed with design the deviation from the designs to use the default material dialog.
iOS
android
* Ran locally & shared WIP with design

feat(android.FavoriteConfirmationDialog): Style as AlertDialog

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt

_Ticket:_ No ticket, based on [report in slack](https://mbta.slack.com/archives/C05QMG9GS9M/p1748627972953529)
We are sometimes unexpectedly treating the 15 as unbranched and always showing a headsign of "St Peter's Square" even for "Fields Corner" trips. This seems to only occur if the next two trips are both heading to "St Peter's Square". 
We want to only look at the first two bus trips to determine whether to use branching rules in nearby transit, but in filtered stop details, we should look at all trips.
iOS
android
* Added a unit test
* Ran locally and confirmed I see other headsigns for the 15, even when the next 2 trips are both to "St Peter's Square"

fix(RouteCardData.potentialService): Evaluate all upcoming trips for bus in unfiltered stop details

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToAlertsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToAlerts.kt
gradle/libs.versions.toml
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosAppTests/Views/ContentViewTests.swift
shared/build.gradle.kts
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/AppModule.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/UsecaseDI.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Alert.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Facility.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/ObjectCollectionBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/AlertsStreamDataResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/GlobalResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/AlertsRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/GlobalRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/usecases/AlertsUsecase.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/response/AlertsStreamDataResponseTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/GlobalRepositoryTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/usecases/AlertsUsecaseTest.kt

_Ticket:_ First piece of [Update elevator alert template text [front-end changes]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210165100251910?focus=true)
This adds `Facility` objects to the frontend, and adds a usecase layer to wrap the alert stream, which injects facility data from the global response directly into the alerts which reference a facility in their informed entities.
We took this approach since we want to use the facility data in `FormattedAlert`, where it would be annoying to prop drill global data everywhere it's used.
Existing tests pass, added unit tests for the new usecase.

feat: Add facilities data to alerts

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/AlertCardTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/FormattedAlert.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Utils/FormattedAlert.swift
iosApp/iosAppTests/Views/AlertCardTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/ObjectCollectionBuilder.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/usecases/AlertsUsecaseTest.kt

_Ticket:_ [Update elevator alert template text [front-end changes]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210165100251910?focus=true)
Follow up to #1034 
Update elevator alert header text to use a localized template which includes the facility short name, instead of the alert header.
iOS
android
Added unit tests for new header text

feat: Elevator alert headers

---

iosApp/iosApp/ContentView.swift
iosApp/iosApp/Pages/Map/AnnotatedMap.swift
iosApp/iosApp/Pages/Map/HomeMapView.swift
iosApp/iosAppTests/Views/ContentViewTests.swift

_Ticket:_ [ Fix Mapbox attribution](https://app.asana.com/1/15492006741476/project/1205425564113216/task/1210440278891490?focus=true)
The position wasn't updated properly when we changed the sheet detent. This should better handle any future detent ratio changes, and stops using the deprecated `UIScreen.main.bounds`, which was giving a number that didn't line up with the actual rendered content height. 
iOS
Tested on an simulated iPhone 16 and an iPhone 13 mini to check that it works on different screen sizes. Also took screenshots and measured pixel lengths between the attribution logo/info button and borders to get consistent …

fix(iOS): Mapbox attribution positioning

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/SubscribeToVehiclesTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/subscribeToVehicles.kt
gradle/libs.versions.toml

_Ticket:_ [🤖 | Fix: missing vehicle pucks](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210444251184038?focus=true)
I was having some trouble reproducing this, so I added 3 separate changes that could make some difference.
* Upgraded mapbox from 11.12.0 to 11.12.2 (there was a [view annotation fix](https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.12.2) in there)
* Add `ignoreCameraPadding(true)` to the annotations so that they always stay visible to the edges of the screen
* Filter out irrelevant GL vehicles when you're on a branch, so that vehicles on parallel branches aren't shown on the map (we already do this on iOS but forgot to ever add it on Android)
android
~- [ ] …

fix(Android): Disappearing vehicle pucks

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/MapAndSheetPageTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/MapLayerManager.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/MapViewModel.kt
iosApp/iosApp/Pages/Map/HomeMapView.swift
iosApp/iosApp/Pages/Map/HomeMapViewHandlerExtension.swift
iosApp/iosApp/Pages/Map/HomeMapViewLayerExtension.swift
iosApp/iosApp/Pages/Map/MapLayerManager.swift
iosApp/iosApp/ViewModels/MapViewModel.swift
iosApp/iosAppTests/Mocks/MockLayerManager.swift
iosApp/iosAppTests/Views/HomeMapViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/MapExp.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/MapTestDataHelper.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/StopFeaturesBuilder.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/StopLayerGenerator.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/style/Exp.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/style/LetVariable.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/GlobalMapData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/map/StopFeaturesBuilderTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/map/StopLayerGeneratorTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/map/style/ExpEval.kt

_Ticket:_ [Omit bus stops on unselected routes below zoom 15](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210277504456915?focus=true)
An alternative approach to #1031 that feels more responsive.
iOS
android
Checked that the bus stops disappear and reappear as called for. Added new unit tests.

feat: hide irrelevant bus stops in layer

---

.github/actions/setup/action.yml
.github/workflows/build-ios.yaml
.github/workflows/test-ios.yaml
iosApp/iosApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
iosApp/project.yml

_Ticket:_ none
Since the ViewInspector fix for Xcode 16.3 has been shipped, we can now upgrade to that version, which might be enough to unblock #922.
Checked that the tests pass.

build: upgrade Xcode and SwiftPM dependencies

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/CollapsableStopListTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/StopListRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/CollapsableStopList.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRow.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopList.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/GlobalResponse.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopListTest.kt

_Ticket:_ [🤖 | Favorites | Collapse non-typical bus stops](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210389717064826?focus=true)
* Collapses non-typical stops in the route list. Leaves some placeholders for improving the accessibility VoiceOver behavior after further discussion with design - will make a ticket to follow up on that.
iOS
android
* Ran locally

feat(android.RouteStopListView): Collpase non-typical stops

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/MapAndSheetPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/retryable/RetryableComposeTestRule.kt

_Ticket:_ [🤖 systematic flaky test rethink](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210425090924778?focus=true)
Adds a retryable rule, useful for testing flaky tests locally and handling one-off flaky tests. Goes along with [WIP flaky test troubleshooting doc](https://www.notion.so/mbta-downtown-crossing/Test-Troubleshooting-551faaa2f7b14fbdafa9214f63e5f816?source=copy_link#20af5d8d11ea80f5b98cd3cc43c4d8b6)
Limitations:
* Logs about retry attempts are only visible when viewing Logcat locally and cannot be accessed from CI.
Next steps:
* Remove reties at the test suite level and add retries to a few specific flaky tests
* Try restructuring the known flaky tests to remove flakiness.
iOS
android
* Added a simple …

feat(android): UI Test rule to retry individual test

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopList.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopListTest.kt

_Ticket:_ [🤖 | Favorites | Route details line broken on inbound bus routes ](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210504151095128?focus=true)
* Inbound bus route lines were broken. This is because an outbound pattern was being chosen as the authoritative pattern to determine what the primary line to draw should be. Now, we filter the list of patterns considered to match the chosen direction.
iOS
android
* Ran locally and confirmed inbound direction shows line as appropriate
* Added a unit test

fix(android.RouteStopListView): Don't pick a pattern in opposite direction as authoritative

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/UpcomingTripViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/TripInstantDisplayExtension.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/MinutesFormat.kt

_Ticket:_ Can of worms found during [[screen reader text for crossed out CR schedule times]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210503750238562?focus=true)
Implement a `MinutesFormat` class in shared code, so that we can use it to get rid of duplicate logic when the changes are implemented in iOS. All the added screen reader text strings already existed in iOS, they just weren't being used in Android.
iOS
android
Added a couple new tests and a couple new content description checks to existing tests

fix(Android): Add > 1 hr departure TalkBack text

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/GlobalResponse.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/response/GlobalResponseTest.kt

_Ticket:_ [🤖 Favorites | Destinations in route details confirmation modals ](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210560254436168?focus=true)
Rather than using the route-level directions in the favorites confirmation modal from the route details page, use the stop-level directions with customized direction labels.
iOS
android
* Ran locally and confirmed for a handful of stops

fix(android.RouteStopListView): correct direction labels in confirmation per stop

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/UpcomingTripViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/PredictionRowView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStatus.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/TripInstantDisplayExtension.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/Favorites/FavoritesView.swift
iosApp/iosApp/Utils/TripInstantDisplayExtension.swift
iosApp/iosAppTests/Views/UpcomingTripViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt

_Ticket:_ [[screen reader text for crossed out CR schedule times]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210503750238562?focus=true), finally
See #1077, #1081, #1085
Add screen reader text on Android and iOS for the CR delay states. Doing this made me catch a few different issues with the existing screen reader text, including missing vehicle types in most places, and duplicate information being read out due to components not being merged.
iOS
android
Existing tests pass, added new unit tests for added functionality

feat: Add screen reader text for the CR delayed/early prediction states

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/map/StopLayerGenerator.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/map/StopLayerGeneratorTest.kt

_Ticket:_ [Show selected stop and pin at all zoom levels](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210456691287467?focus=true)
Nice and easy.
iOS
android
Checked that the selected stop shows up on the map at all zoom levels on both iOS and Android.

feat: show selected stop at any zoom

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/ActionButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/NavTextButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/favorites/FavoritesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/EditFavoritesPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MorePage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routePicker/RoutePickerView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilterPills.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/ButtonDefaultsExtension.kt

_Ticket:_ No ticket, detour on [🤖 | Favorites Route Details layout UI](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210485399858975?focus=true)
We had a bunch of duplicated button color objects, this consolidates all the reused ones into extensions on `ButtonDefaults`.
android
Not testable

refactor(Android): Consolidate button colors

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/StopListRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/CollapsableStopList.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/DirectionPicker.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripStops.kt

_Ticket:_ [🤖 | Favorites Route Details layout UI](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210485399858975?focus=true)
Follow up to https://github.com/mbta/mobile_app/pull/1098 and https://github.com/mbta/mobile_app/pull/1110
This includes a few discrete changes:
* Update direction toggle to match spec, this involved left aligning destinations unless there is no destination label, in which case center on both axes
* The route details stop rows had excess padding on the sides, which included padding around the halo separators between rows, which was awkward to fix because the trip stop list really heavily relies on that padding
* Implement the GL route picker UI
I didn't do the background flood route color, but confirmed that it's blocked on [🤖 | Refactor sheet …

feat(Android): Route details polish and GL picker

---

gradle/libs.versions.toml

_Ticket:_ none
I just got an Android Studio warning about [16 KB page size support](https://developer.android.com/guide/practices/page-sizes), which Google Play will start requiring in November and which Mapbox doesn’t provide by default. [Evidently](https://github.com/mapbox/mapbox-maps-android/issues/2448), Mapbox had been using the Android NDK 23, which doesn’t support 16 KB page sizes and would’ve been a breaking change to just upgrade from, so they’re publishing `-ndk27` versions of most of their packages, and if we move to those now then we should be ready for the requirement coming in November.
iOS
android
Checked that the Android Studio APK analyzer says the Mapbox shared libraries are aligned to 16 KB and that the map still works.

chore: use Android NDK 27 builds of Mapbox

---

iosApp/iosApp/Pages/StopDetails/StopDetailsFilteredDepartureDetails.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsFilteredDepartureDetailsTests.swift

_Ticket:_ [Bug: Stop Details | Next trip selected before current trip disappears](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210616350159111?focus=true)
This PR resolves the bug with selecting the next trip before the current trip disappears by updating the leaf format when now changes. This is consistent [with the implementation in android](https://github.com/mbta/mobile_app/blob/a28cb0921ade1eb87b024125900b5edb4df8f3a3/androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesView.kt#L71).
The reason the trip filter is correctly accounting for now is that autoTripFilter calculates the leaf format too, [using the latest value of now](https://github.com/mbta/mobile_app/blob/a28cb0921ade1eb87b024125900b5ed …

fix(ios.StopDetailsFilteredDepartureDetails):  Recalculate leaf format when now changes

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/RoundedCornerColumn.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlay.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/EmptyStateView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/LoadingResultsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/RouteResultsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/SearchResultsView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/StopResultsView.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/Search/Results/LoadingResultsView.swift
iosApp/iosApp/Pages/Search/Results/SearchResultsView.swift
iosApp/iosAppTests/Views/SearchResultViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/LoadingPlaceholders.kt

_Ticket:_ [🤖 Search | Implement empty/error search result states](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210561875928847?focus=true)
I went ahead and rearranged the Android component structure to be slightly more structurally similar to the iOS component structure while I was in there.
iOS
android
Checked that empty state and error text displays correctly and is translated on both iOS and Android.

fix: align search loading/error/empty between iOS and Android

---

README.md
bin/placeholder-translations.py

_Ticket:_ none
Realized during #1118 that there has to be a better way.
The ceiling on how good this can be is higher than I’ve reached right now — automatically polling `pbpaste` until it’s changed would simplify the tail end, writing and reading to a Google Sheet directly via the Google Sheets API would be simpler to work with, and plurals are probably achievable — but this seems like it’s still pretty simple.
iOS
android …

dev: add helper script for placeholder translations via Google Sheets

---

iosApp/iosApp/ComponentViews/RouteCard/RouteCard.swift
iosApp/iosApp/Pages/Search/Results/SearchResultsView.swift
iosApp/iosAppTests/Views/RouteCardTests.swift

_Ticket:_ [ | Favorites | Remove star from route card behind flag](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210559767128756?focus=true)
Remove the legacy pin buttons when you have the feature flag for new favorites enabled.
iOS
Updated and added tests for the pin button

feat(iOS): Remove pin stars on route cards when enhanced favorites is selected

---

iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitViewTests.swift

_Ticket:_ [ | Favorites | Don't consider favorites when sorting nearby transit](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210559766928410?focus=true)
iOS version of https://github.com/mbta/mobile_app/pull/1037
iOS
android
* Ran locally and confirmed that pinned routes aren't sorted to the top with enhanced favorites on

 feat(ios.NearbyTransitView): Don't sort by pinned when enhancedFavorites 

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/AppModule.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/FavoritesViewModel.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/FavoritesViewModelTest.kt
shared/src/iosMain/kotlin/com/mbta/tid/mbta_app/Helpers.kt

_Ticket:_ [favorites flaky molecule tests](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210621071746794?focus=true)
<details><summary>Pre-Review</summary>
This PR takes an approach for addressing flakiness in Molecule VM tests. There may be other approaches we want to consider instead, but this is is a first step towards solving the problem. 
This PR combines approach #2 and #4 as outlined [in slack here](https://mbta.slack.com/archives/C062QNAJZ2M/p1750874718166159)
> 2. Use [runCurrent() + expectMostRecent()](https://github.com/cashapp/turbine/issues/246#issuecomment-1674281572) instead of awaitItemSatisfying to get the last item that should match the desired state rather than the first (except I used advanceUntilIdle() instead of …

fix(shared.FavoritesViewModelTest): Address flakiness

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt

_Ticket:_ [🤖 | Favorites | Add stops flow - Tap stars toast](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210229158900372?focus=true)
Follow up to #1095 
This fixes an issue in the add favorites flow, where the first time toast will stick around after you go back, until you dismiss it. The back functionality wasn't implemented when the toast stuff was done, so I missed it after merging in main.
android
Split out the back and close functionality into separate tests, each with a check to ensure that the toast is closed.

fix(Android): Hide fav hint toast on back nav

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
fastlane/Fastfile
iosApp/iosApp/ComponentViews/StopListRow.swift
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Pages/RouteDetails/RouteDetailsView.swift
iosApp/iosApp/Pages/RouteDetails/RouteStopListView.swift
iosApp/iosApp/Pages/Search/Results/RouteResultsView.swift
iosApp/iosApp/Pages/Search/Results/SearchResultsContainer.swift
iosApp/iosApp/Pages/Search/Results/SearchResultsView.swift
iosApp/iosApp/Pages/StopDetails/DirectionPicker.swift
iosApp/iosApp/Pages/StopDetails/TripStopRow.swift
iosApp/iosApp/Utils/SheetNavigationStackEntry.swift
iosApp/iosAppTests/Pages/RouteDetails/RouteStopListViewTests.swift
iosApp/iosAppTests/Views/SearchResultViewTests.swift

_Ticket:_ [ | Favorites | Route details - basic UX](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210440278891515?focus=true)
Ported over the component structure from Android, and moved the iOS TripStopRow into StopListRow. Includes the non-GL branching because it’d’ve been more work to separate that out.
iOS
android
Ported over relevant tests from Android. Checked that page works.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210559767128765

feat(iOS): route details UX

---

iosApp/iosApp/Pages/RouteDetails/CollapsableStopList.swift
iosApp/iosApp/Pages/RouteDetails/RouteStopListView.swift
iosApp/iosAppTests/Pages/NearbyTransit/NoNearbyStopsViewTests.swift
iosApp/iosAppTests/Pages/RouteDetails/CollapsableStopListTests.swift
iosApp/iosAppTests/Pages/RouteDetails/RouteStopListViewTests.swift
iosApp/iosAppTests/Pages/StopDetails/ExplainerPageTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsFilteredDepartureDetailsTests.swift
iosApp/iosAppTests/Pages/StopDetails/StopDetailsNoTripCardTests.swift
iosApp/iosAppTests/Pages/StopDetails/TripHeaderCardTests.swift
iosApp/iosAppTests/Pages/StopDetails/TripStopRowTests.swift
iosApp/iosAppTests/Pages/StopDetails/TripStopsTests.swift
iosApp/iosAppTests/ViewInspectorExtensions.swift
iosApp/iosAppTests/Views/AlertCardTests.swift
iosApp/iosAppTests/Views/RouteCardTests.swift
iosApp/iosAppTests/Views/UpcomingTripViewTests.swift

_Ticket:_ [ | Favorites | Collapse non-typical bus stops](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210559767128761?focus=true)
Did this as part of #1123; splitting it out for very slightly easier review, since it’s the only piece I could think of that really separates out cleanly.
Also includes a bonus refactor for finding images by name in ViewInspector.
iOS
android
Ported over the Android unit tests. Checked that the stops collapse.

feat(iOS): collapsing rare stops in route details

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/RecenterButton.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModel.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModelTests.kt

_Ticket:_ [🤖 Fix vehicle centering on stop details](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210733324373948?focus=true)
Fixes vehicle overview on stop details, recentering on current location in vehicle overview mode, and the click ripple going beyond the recenter button boundaries.
Existing tests pass and tweaked recenter test a bit.

fix(Android): Fix stop details vehicle overview

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/SheetHeader.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/favorites/FavoritesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/EditFavoritesPage.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/ComponentViews/NavTextButton.swift
iosApp/iosApp/ComponentViews/SheetHeader.swift
iosApp/iosApp/ContentView.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/Favorites/EditFavoritesPage.swift
iosApp/iosApp/Pages/Favorites/FavoritesView.swift
iosApp/iosApp/Utils/SheetNavigationStackEntry.swift
iosApp/iosAppTests/Pages/Favorites/EditFavoritesPageTests.swift
iosApp/iosAppTests/Pages/Favorites/FavoritesViewTests.swift
iosApp/iosAppTests/Views/SheetHeaderTests.swift

_Ticket:_ [ | Favorites | UX | Delete favorites](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210440278891503?focus=true)
This PR is the first chunk of adding navigation into the edit favorites flow. I opted to do a little refactoring to add the action buttons into the existing SheetHeader component and adopt that on android as well, so breaking this off here for review.
iOS
android
* Ran locally on iOS & android
* Added some simple unit tests to build on in next PR

feat(ios.FavoritesPage): Edit favorites entrypoint

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModel.kt

_Ticket:_ [🤖 | v1.2.6 QA | Selected bus route shape doesn't stay visible](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210793281349693?focus=true)
* Ensures that when a vehicle is selected, the route shape no longer flickers in and out. 
The order of operations prior to this change was:
1. handleNavChange called with selected stop & stop filter
2. handleNavChange called with selected stop, stop filter, trip filter
3. selectedVehicle called with selected stop & stop filter, but the stop filter was dropped by the VM. 
This repairs step 3 by preserving the stopFilter when in the `SelectedVehicle` state.
iOS
android
* Ran locally on android, confirmed that the shape of the vehicle persists as expected
* Haven't written …

fix(shared.MapViewModel): Don't clear stopFilter when vehicle is selected

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/SearchInput.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/SheetHeader.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/sheet/BottomSheetScaffold.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/favorites/FavoritesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/favorites/NoFavoritesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routePicker/RoutePickerView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredSheetHeader.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredRoutesView.kt

_Ticket:_ [🤖 | Refactor sheet handle](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210561875928843?focus=true)
Before this, the sheet handle at the top of the sheet was taking up vertical space that the sheet content could not access, which meant that the sheet background color couldn't easily be controlled on a per page level, and that the sheet headers couldn't take up space underneath the handle.
I realized in the middle of this that the hard part wasn't the sheet handle itself, but the excess space that the sheet takes up when expanded to max size. I got around this by wrapping all of the sheet route views in a simple `SheetPage` component, which conditionally adds the top padding but draws the background color based on a param passed in which has the context …

feat(Android): Sheet handle & background refactor

---

iosApp/iosApp/ContentView.swift

_Ticket:_ [ | v1.2.6 QA | Toggling from map display off → on breaks map](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210793281349699?focus=true)
When hideMaps was switched from false to true, the navigation was getting stuck in a mismatched state because when the fullScreenCover switched to the other one, the old one being dismissed and navigating backwards, even though it should have been staying on the more page.
It took me a while to find but I'm so glad the fix was this simple.
iOS
Manually toggled hide maps on and off repeatedly, switching back and forth between all possible navigation, with …

fix(iOS): hideMaps sheet navigation bug

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/SaveFavoritesFlowTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/SaveFavoritesFlow.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/EditFavoritesPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/ComponentViews/SaveFavoritesFlow.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/RouteDetails/RouteStopListView.swift
iosApp/iosAppTests/Pages/RouteDetails/RouteStopListViewTests.swift
iosApp/iosAppTests/Views/SaveFavoritesFlowTest.swift

_Ticket:_ [🤖 | Favorites | Fix: route-specific findings](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210755319204273?focus=true)
This PR addresses 3 small QA findings for edge case routes
1. Disclaimer when trying to add a stop with no service
2. Android only - trash icon missing in edit favorites when long headsign
3. All stops collapsed as less common when no typical pattern
iOS
android
| Case | Android | iOS |
|--------|--------|--------|
| 1. Drop-of only (also unit tested) Forced case for iOS at park st since add favorites not implemented yet for SL | <img width="640" height="1386" alt="image" src="https://github.com/user-attachments/assets/abc49a9e-5074-4226-8954-9836876a9746" /> | <img width="1170" …

fix: misc. route-specific edge case favorites QA 

---

iosApp/iosApp/Utils/SettingsCache.swift

_Ticket:_ [EXC_BREAKPOINT: calling into SwiftUI on a non-main thread is not supported > Fatal error > SwiftUI/ThreadUtils.swift](https://app.asana.com/1/15492006741476/project/1209332220656329/task/1210848967577589?focus=true)
This fixes a crash on prod due to setting the published `cache` var from a background thread. 
iOS
android
* Ran locally, confirmed I no longer see a purple warning about the background thread at this line, whereas I do on main. 
I did see some other purple run warnings at one point which I'm also no longer seeing (on this branch or on main), so want to see if I can trigger those again, but this contains the immediate fix.

fix(ios.SettingsCache): Load settings as MainActor

---

androidApp/build.gradle.kts

Bump to 1.2.7 to prep for the [Event buffer overflow MapViewModel](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210857402669010?focus=true) hotfix release

chore(Android): 1.2.7

---

androidApp/build.gradle.kts

There were still mismatched versions in #1168, setting this to try to match `sentry-android`.
```
The Sentry SDK has been configured with mixed versions. Expected maven:io.sentry:sentry-android to match core SDK version 8.17.0 but was 8.15.1
```

fix(Android): Downgrade defined sentry version

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/CollapsableStopListTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetRouteStopsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/CollapsableStopList.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getRouteStops.kt
iosApp/iosApp/Pages/RouteDetails/CollapsableStopList.swift
iosApp/iosApp/Pages/RouteDetails/RouteStopListView.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/RepositoryDI.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/LoadingPlaceholders.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteBranchSegment.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopList.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/RouteStopsRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopListTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/RouteStopsRepositoryTest.kt

_Ticket:_ [🤖 | Favorites | Route Details Branching implementation](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210764630199366?focus=true)
Consumes https://github.com/mbta/mobile_app_backend/pull/341 / https://github.com/mbta/mobile_app_backend/pull/342 in a parallel code path that nothing calls yet. I’ve already done the Android work, so I know this is the set of functionality that’s needed for the Android work, but I rearranged a couple of things as part of splitting out this PR separately, so it may be another bit before the Android stacked PR appears.
Also, I know I said this wasn’t going to be a 2,000 line PR, but after splitting out the shared work I added back in the old path (and adding is more lines than replacing) and I wrote tests for …

feat: shared code for final route branching approach

---

fastlane/Fastfile

_Ticket:_ [iOS: Add external dev-orange tester group to dev-orange app CI](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210752448933675?focus=true)
Does the thing.
iOS
android
Not tested.

build: send iOS dev-orange builds to correct groups

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/NearbyRepository.kt

_Ticket:_ [Investigate: nearby stop sort order](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210845316775461?focus=true)
The list of stop IDs going into `filterStopsWithRedundantPatterns` was sorted by distance, but the list coming out gets pieced together from a set and map, which lost the distance context. In most cases this was fine, because another distance sort happens during route card data creation, but in cases like the GL at Hynes, there are multiple bus routes which have a nearest stop at Kenmore. Since the GL Kenmore platforms were also within the radius and the bus routes patterns were being processed first, the GL Kenmore platforms were being returned above Hynes, then the route card processing would assume that was the closest GL stop and filter out …

fix: Order nearby stops after filtering

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RoutePattern.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/FavoritesViewModel.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RoutePatternTest.kt

_Ticket:_ [Favorites | Investigate favorites ordering further stops above closer ones](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210846540627388?focus=true)
We were seeing an issue where some routes in favorites were being sorted higher than other routes when their closest stop was further away. This was happening when there was a favorite at a closer stop which also served the further route (ex, with a location set near Harvard, the 71 bus at Harvard would cause RL at Park to be sorted to the top). 
This was caused because we were performing the full route card creation (and sorting) with every route at any favorited stop, then filtering the route card data down at within the favorites VM to the actual set of favorites. After this change, the filtering at the …

fix: Filter favorites during route card creation

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/ContentViewModelTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/ContentViewTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/ContentViewModel.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/SheetRoutes.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/BottomNavBar.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/SheetHeader.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/SettingsCache.kt
shared/src/androidMain/kotlin/com/mbta/tid/mbta_app/viewModel/viewModelModule.android.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/AppModule.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/RepositoryDI.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/LoadingPlaceholders.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/DefaultTabRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/TabPreferencesRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/FavoritesViewModel.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/TabPreferencesRepositoryTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/FavoritesViewModelTest.kt
shared/src/iosMain/kotlin/com/mbta/tid/mbta_app/viewModel/viewModelModule.ios.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/viewModel/viewModelModule.jvm.kt

_Ticket:_ [ 🤖 | Favorites | Default to favorites first time only](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210767320164830?focus=true)
This PR includes the android implementation for defaulting to favorites the first time only. As [discussed in slack](https://mbta.slack.com/archives/C062QNAJZ2M/p1753384488495949), using a new repo to determine whether the user has viewed favorites or not rather than tying it to the launch promo. 
There was a bit of UI jankiness to work through for this new loading state on android, so breaking it off here for review before addressing possible UI jank on the iOS side. 
iOS
android
* Ran locally, simulating version 2.0.0 with enhancedFavorites setting forced to …

feat(android): Default to favorites first time only

---

iosApp/iosApp/ComponentViews/SaveFavoritesFlow.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/RoutePicker/RoutePickerView.swift
iosApp/iosApp/Utils/FormattedAlert.swift

_Ticket:_ none
When we implement a new feature on Android first and iOS later, Xcode never clears the manually-added flag on strings which were manually added for Android and then later also used from iOS. This isn’t actually bad, but it does cause the comments specified in iOS to not be written to the .xcstrings, which can be confusing and annoying.
iOS
android
Checked that if any more `"extractionState": "manual"` strings …

chore: reset manually extracted state in Localizable.xcstrings

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/CollapsableStopListTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/state/GetRouteStopsTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/StickDiagram.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/CollapsableStopList.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/state/getRouteStops.kt
iosApp/iosApp/ComponentViews/RouteLineTwist.swift
iosApp/iosApp/ComponentViews/StickDiagram.swift
iosApp/iosApp/ComponentViews/StopListDisclosureGroup.swift
iosApp/iosApp/Pages/RouteDetails/CollapsableStopList.swift
iosApp/iosApp/Pages/RouteDetails/RouteStopListView.swift
iosApp/iosApp/Pages/StopDetails/TripStops.swift
iosApp/iosApp/Utils/CGRectExtension.swift
iosApp/iosApp/Utils/PathPointExtension.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/RepositoryDI.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/endToEnd/EndToEndRepositories.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/LoadingPlaceholders.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopList.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/RouteStopsRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/shape/CrossPlatformPathTypes.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/shape/StickDiagramShapes.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopListTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/RouteStopsRepositoryTest.kt

_Ticket:_ none
Removes all the “Old” stop list logic, moves the branching diagram path math to shared code, and tweaks the twist/untwist animation a little bit.
iOS
android
Checked that the animation looks correct and smooth on both Android and iOS in both trip details and route details.

chore: route branching cleanup

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreSectionView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
bin/placeholder-translations.py
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/More/MoreSection.swift
iosApp/iosApp/Pages/More/MoreSectionView.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/morePage/MoreSection.kt

_Ticket:_ [Add TTY/ASL contact info to More tab](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210919282215089?focus=true)
Screenshots [in Slack](https://mbta.slack.com/archives/C05QMG9GS9M/p1753891258860369?thread_ts=1753891214.362909&cid=C05QMG9GS9M).
iOS
android
Checked that the new text is displayed on both Android and iOS.

feat: show TTY/ASL instructions alongside support number

---

iosApp/iosApp/Launch Screen.storyboard

_Ticket:_ [ Favorites | UI Polish](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210710490021005?focus=true)
This just includes the added tab in the storyboard, no other pieces. 
Storyboards are annoying, I'm glad we don't have to edit these more. As part of this, I made it so that the selected tint color is Deemphasized, so that none of the tabs appears selected on the launch screen.
iOS
Confirmed that it shows up on launch, and matches the layout when the actual app loads

feat(iOS): Add favorites to launch screen

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt
iosApp/iosApp/ComponentViews/HaloSeparator.swift
iosApp/iosApp/ComponentViews/RouteCard/RouteCardList.swift
iosApp/iosApp/ComponentViews/SheetHeader.swift
iosApp/iosApp/ComponentViews/StopListRow.swift
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/Favorites/EditFavoritesPage.swift
iosApp/iosApp/Pages/Favorites/FavoritesPage.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitPage.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/RouteDetails/RouteDetailsView.swift
iosApp/iosApp/Pages/RouteDetails/RouteStopListView.swift
iosApp/iosApp/Pages/StopDetails/DirectionPicker.swift
iosApp/iosApp/Utils/HaloScrollView.swift
iosApp/iosApp/Utils/Typography.swift
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitPageTests.swift

_Ticket:_ Prep for [ Favorites | UI Polish](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210710490021005?focus=true)
In addition to getting route details closer to spec, this also adds a HaloScrollView which displays a halo separator at the top of the scroll area when the contents are scrolled down, and this was added in most of the places where it makes sense (I didn't add it to the route picker since that's actively being worked on).
I also removed the nearby transit "Select location" loading spinner and card, since it's not in the spec, was broken at small detent, was inconsistent with Android (and favorites), and resulted in multiple loading states flickering when moving the map.
iOS
~- [ ] If you added any user-facing strings on iOS, are they included in …

feat(iOS): Route details UI implementation

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/containsWrappableText.kt
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingTrip.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplayTest.kt

_Ticket:_ [Display scheduled Commuter Rail times with status when prediction has null times but non-null boarding_status](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210826290372849?focus=true)
It seems like, if we want to show schedules in the past that still have a status, it’d also be correct to show predictions in the past that still have a status.
iOS
android
Added unit tests for new logic. …

fix: show status for CR even for times in the past

---

iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/RoutePicker/RoutePickerView.swift
iosApp/iosApp/Pages/Search/SearchField.swift
iosApp/iosApp/Pages/Search/SearchInput.swift
iosApp/iosAppTests/Pages/RoutePicker/RoutePickerViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SearchResultRepository.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/SearchRoutesViewModel.kt

_Ticket:_ [ | Favorites |  Add stops flow - search / filter](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210765282940767?focus=true)
Adds search/filter functionality to the add stops flow.
iOS
Added tests for new states.

feat(iOS): Search for add stops flow

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/GlobalMapData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/LeafFormat.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/UpcomingFormat.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Vehicle.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/AlertsStreamDataResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/GlobalResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/MapFriendlyRouteResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/PredictionsByStopJoinResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/PredictionsByStopMessageResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/PredictionsStreamDataResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/ScheduleResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/SearchResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/StopMapResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/TripSchedulesResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/response/VehiclesStreamDataResponse.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/EasternTimeInstant.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt

_Ticket:_ [ | Improve shared object comparisons to eliminate slow `.toString` operations](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210790508156212?focus=true)
I don’t think this comes from comparisons, but I’m not sure anymore what it comes from instead. I was having trouble finding any massive time costs in `toString`s at all, and then I added View Properties profiling and started seeing more time in `toString`s, so I thought it was the View Properties profiling retrieving the debugDescriptions of state objects, but then I removed the View Properties profiling and was still seeing more time in `toString`s. 🤷‍♀️ 
This may make debugging test failures slightly more difficult, but commenting out the overridden `toString` of the relevant class will restore the …

fix: speed up toString calls

---

iosApp/iosApp/Pages/Search/Results/SearchResultsContainer.swift
iosApp/iosAppTests/Views/SearchResultViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/SearchViewModel.kt

_Ticket:_ No ticket, fixes a flaky test that has prevented a couple of merges, like in https://github.com/mbta/mobile_app/pull/1198
The failing test runs had a confusing error that was a mix of two tests
```
[19:33:32]: ▸ ::error file=/Users/runner/work/mobile_app/mobile_app/iosApp/iosAppTests/Views/SearchResultViewTests.swift,line=54::    testDisplaysTrips, API violation - multiple calls made to -[XCTestExpectation fulfill] for getSearchResults. (NSInternalInconsistencyException)
```
In the referenced SearchResultViewTest, it *is* possible for `getSearchResults` to be called multiple times, because it is [triggered from a LaunchedEffect with 3 inputs](https://github.com/mbta/mobile_app/blob/d99d345f1582a20a315c009dfddf704f004f05de/shared/src/commonMain/kotlin/com/mbta …

fix(ios.SearchResultViewTests): Stabilize flaky test

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/UpcomingTripViewTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/PredictionRowView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/UpcomingTripView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCard.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/DepartureTile.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/TripInstantDisplayExtension.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/containsWrappableText.kt
iosApp/iosApp/ComponentViews/PredictionRowView.swift
iosApp/iosApp/ComponentViews/UpcomingTripView.swift
iosApp/iosApp/Pages/StopDetails/DepartureTile.swift
iosApp/iosApp/Utils/TripInstantDisplayExtension.swift
iosApp/iosAppTests/Views/UpcomingTripViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplay.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataLeafTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripInstantDisplayTest.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/ProjectUtils.kt

_Ticket:_ [Display scheduled Commuter Rail times with status when prediction has null times but non-null boarding_status](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210826290372849?focus=true)
Adds the formatting in nearby transit called for in [Adam’s mockup](https://mbta.slack.com/archives/C05QMG9GS9M/p1754346288816529?thread_ts=1754073004.733619&cid=C05QMG9GS9M) that was deferred in #1195, plus adds some previews and tests so we can be more confident that this actually works even in the absence of real issues to hit this case.
iOS
android
- ~~[ ] All user-facing strings added to strings resource …

fix: follow-up work on commuter rail status

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListView.kt

_Ticket:_ [🤖 | RouteStopListView showFavoritesStopConfirmation is rememberingSaveable a Stop](https://app.asana.com/1/15492006741476/project/1205425564113216/task/1211001075059985?focus=true)
[Sentry issue](https://mbtace.sentry.io/issues/6675679257/)
Domain objects aren’t saveable with the default saver, and instead of checking this at compile time, this is just a perpetual sword of Damocles at runtime.
iOS
android
Checked …

fix(Android): don’t `rememberSaveable` a `Stop?`

---

androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
buildSrc/src/main/kotlin/com/mbta/tid/mbta_app/gradle/ConvertIosLocalizationTask.kt
iosApp/iosApp/Localizable.xcstrings

_Ticket:_ ["arriving at %1$@" placeholder translations reference %2$@ instead](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211001463064536?focus=true)
This popped up in Sentry and wasn’t particularly difficult to fix and catch earlier.
iOS
android
Checked that with mismatched placeholders the conversion step will correctly fail.

fix: resolve and detect translated strings with different placeholders

---

Gemfile
Gemfile.lock
fastlane/Fastfile

_Ticket:_ [🤖 | Set up sentry releases](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210889278584728?focus=true)
Set sentry release version with Fastlane.
Ran pipeline to build for dev orange without the check to skip creating versions on prod, and version was created successfully in Sentry with the proper version code.

feat(Android): Set Sentry release version

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/routePicker/RoutePickerView.kt
iosApp/iosApp/Pages/RoutePicker/RoutePickerView.swift

_Ticket:_ [ | Favorites | Address UI QA - Search](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211025684993052?focus=true)
This PR resets the scroll position for route search results when the results change. 
I looked into addressing the AC "don't drop the background when keyboard opens" for a bit, but didn't find a suitable workaround. It looks like this is the default behavior of a `TextField` in a sheet to accommodate the keyboard height. It is not respecting our system-defined max detent of the sheet which is surprising, and also makes it seems not worth too much effort to try and resolve.
iOS
android
* Ran locally, searched & scrolled repeatedly to ensure scroll position reset

fix: Reset scroll position when search results change

---

iosApp/iosApp/ComponentViews/RouteCard/LoadingRouteCard.swift
iosApp/iosApp/ComponentViews/RouteCard/RouteCard.swift
iosApp/iosApp/ComponentViews/RouteCard/RouteCardDepartures.swift
iosApp/iosApp/ComponentViews/RouteCard/RouteCardList.swift
iosApp/iosApp/Pages/Favorites/FavoritesView.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitPage.swift
iosApp/iosApp/Pages/NearbyTransit/NearbyTransitView.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsUnfilteredView.swift
iosApp/iosApp/ViewModels/NearbyViewModel.swift
iosApp/iosAppTests/Views/RouteCardDeparturesTests.swift
iosApp/iosAppTests/Views/RouteCardTests.swift

No ticket, found while working on [Favorites | Clean up old favorites flows](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210767320164832?focus=true).
On android the [RouteCard uses FavoritesBridge ](https://github.com/mbta/mobile_app/blob/481f807e8acace88556ad003d25d32cf44748f7d/androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCard.kt#L66)so that tapped_departure can set the value for `pinned` whether a favorite is old or new, but on iOS it only looked for the old version of pinned. Since I'm doing away with FavoritesBridge anyway in my next PR, opting to just use `isFavorite(RouteStopDirection)`. 
iOS
~ - [ ] Add …

fix(ios.RouteCardDepartures): tapped_departure event correctly records if isFavorite

---

iosApp/iosApp/ComponentViews/NavTextButton.swift
iosApp/iosApp/Pages/Favorites/FavoritesView.swift

No ticket, found while doing release QA for favorites. The add button was set to scale but edit was not. Updated to scale both together
iOS
android
Ran locally at different text sizes

fix(FavoritesView): Edit & add buttons have same scale

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModel.kt

_Ticket:_ [Event buffer overflow MapViewModel](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211010043650124?focus=true)
This PR *potentially* fixes the event buffer overflow issue we've been seeing in prod. I haven't been able to reproduce this locally, but my best bet is that some events were taking a long time to process and filling up the buffer, contributing to the overflow. 
I added some logging to the duration of processing events (in ms), and found events that affected the map position took > 1s. 
Potentially if a user is tapping around to a bunch of trips and navigating back and forth a lot, this could back up the event queue enough to cause an overflow. 
That is still somewhat speculative since I haven't been able to repro this issue, …

fix?(shared.MapViewModel): Move map side effects into background

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPageTest.kt
iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitViewTests.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt

_Ticket:_ [Impossible direction shown at terminal when alert](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211034220968547?focus=true)
This isn’t actually caused by the alert, but by the absence of scheduled or predicted trips to tell us whether or not service is arrival-only at that stop. Falling back to checking that the stop is the last stop on all its typical route patterns seems like the most robust approach.
iOS
android
- ~~[ ] Expensive calculations are run in `withContext(Dispatchers.Default)` where possible …

fix: treat last stops on typical patterns as arrival-only if no trips exist

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt

_Ticket:_ [Fix: Can't scroll to bottom of favorites](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211117039157377?focus=true)
Oops.
iOS
android
Checked that it’s now possible to scroll all the way down in favorites and nearby transit.

fix(Android): use correct padding for sheet with hide maps

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModel.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModelTests.kt

_Ticket:_ [🤖 | Route shapes & stops hidden after more page](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211055606783875?focus=true)
When moving to the More page and back, the map gets recreated but the ViewModel doesn’t, so a new layer manager is passed into the same ViewModel, and it needs to be actually used.
iOS
android
Checked that this solves the issue. Added a unit test.

fix(Android): add layers to new map when map gets recreated

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt

_Ticket:_ [🤖 | sheet covers search when returning from full-height stop details](https://app.asana.com/1/15492006741476/project/1201654106676769/task/1211055599324062?focus=true)
iOS
android
Checked manually that this fix resolves this issue.

fix(Android): hide sheet if returning to search

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/location/ViewportProviderTest.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/location/ViewportProvider.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt

_Ticket:_ [🤖 | Map animation race condition?](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210805266121129?focus=true)
Ugh.
iOS
android
Checked that some steps that used to sometimes reproduce this issue (have a favorite far away from your current location, expand the favorites sheet, tap that favorite) now do not reproduce this issue. Added a test which fails without the lazy `animateToOverview` …

fix(Android): handle setSheetPadding applying while animateToOverview queued

---

.github/workflows/cache-cleanup.yaml

_Ticket:_ none
Noticed that a lot of our [GitHub Actions cache usage](https://github.com/mbta/mobile_app/actions/caches) is from merge queue branches, and being able to cache things from one attempt at merging a PR to the next is not very useful (if it even works at all, which it might not). It would be nice to just treat the cache as read-only in the merge queue, but there’s no clear way to do that, so the next best thing is to occasionally prune merge queue caches so that they aren’t as likely to crowd out actually useful cache data.
iOS
android
- ~~[ ] All user-facing strings added to strings resource in alphabetical …

ci: clean up caches written by merge queue twice a day

---

iosApp/iosApp/Pages/StopDetails/ExplainerPage.swift
iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift
iosApp/iosApp/Pages/StopDetails/TripDetailsView.swift
iosApp/iosApp/Utils/ExplainerModifier.swift

_Ticket:_ Prep for iOS [Move StopDetailsViewModel to shared code](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210525354862284?focus=true)  
The iOS StopDetailsVM handles the explainer state currently, and this seemed like an easy and discrete thing to split out into a separate PR. Moving it into basic view state doesn't require adding this modifier, but it seemed more concise and reusable. Now the state is managed entirely in TripDetails.
iOS
I started trying to add a couple simple tests, but it looks like testing fullScreenCover requires jumping through a few [ViewInspector …

feat(iOS): Create explainer modifier

---

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/Departures.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCard.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/StopDetailsPage.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredRoutesView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredView.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsView.kt

_Ticket:_ [🤖 | Favorites button animates every time the trip filter changes on stop details](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211176145248868?focus=true)
I thought that I had wired the `null`-when-loading `isFavorite` state all the way through, but apparently not.
The `manageFavorites` state gets reset every time the trip filter changes, because the trip filter change is a navigation to a new page, so this still flickers out when switching trips, which is better than animating but not by much. I tried to fix that with changes to the Android navigation subsystem, but nothing I tried actually worked.
iOS
- ~~[ ] Add temporary machine translations, marked …

fix(Android): don’t animate favorite button when switching trips

---

shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/FavoritesViewModelTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/FlowUtils.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/StopDetailsViewModelTest.kt

_Ticket:_ [CI | android flaky tests again](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211209894303557?focus=true)
The change to FavoritesVM follows an existing flaky molecule fix of broadening the `awaitItemSatisfying` conditions.
The changes to the StopDetailVM are newer territory , since those tests had some extra complexity of testing multiple flows at once. See[ slack thread](https://mbta.slack.com/archives/C062QNAJZ2M/p1757094457414739) about how the existing tests broke the functionality of `awaitItemSatisfying` in mysterious ways. Updating it to only call `awaitItem` from within `awaitItemSatisfying` seems to have made it work more reliably. 
iOS
~- [ ] If you added any user-facing strings on iOS, are they included in …

fix?(shared.VMTests): Address flakiness in molecule tests

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/ContentViewTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/TestUtils.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/alertDetails/AlertDetailsPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/SaveFavoritesFlowTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/routeCard/DeparturesTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCardListTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCardTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/component/routeCard/StopHeaderTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/favorites/EditFavoritesPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/MapAndSheetPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/nearbyTransit/NearbyTransitViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/MorePageTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routeDetails/RouteStopListViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/routePicker/RoutePickerViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlayTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredDeparturesViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsFilteredPickerViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsNoTripCardTests.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsPageTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsUnfilteredRoutesViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/StopDetailsViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsViewTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripStopRowTest.kt
androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/util/SettingsCacheTest.kt

_Ticket:_ [🤖 | Track this Trip | Sheet contents](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210501361218460?focus=true), tangentially
Since the `KoinContext` is only inherited through Compose, it doesn’t make it down to the ViewModels.
iOS
android
Checked that all the tests still pass.

test(Android): load Koin mocks into global Koin so they propagate to ViewModels

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/HomeMapViewTests.kt
shared/src/androidMain/kotlin/com/mbta/tid/mbta_app/viewModel/viewModelModule.android.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModel.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/mocks/MockClock.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModelTests.kt
shared/src/iosMain/kotlin/com/mbta/tid/mbta_app/viewModel/viewModelModule.ios.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/viewModel/viewModelModule.jvm.kt

_Ticket:_ [🤖 | Reflect alerts on the map as quickly as in the sheet](https://app.asana.com/1/15492006741476/project/1201654106676769/task/1211292609179112?focus=true)
iOS
android
Wrote a new test to reproduce the issue that went from failing to passing with this change.

fix(MapVM): use actual current time for alerts if alerts change

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopList.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/TripDetailsStopListTest.kt

_Ticket:_ [Replace hardcoded route ID list with listed_route: false](https://app.asana.com/1/15492006741476/project/1205425564113216/task/1211374343402152?focus=true)
Love a nice 0.1 point task.
iOS
android
Updated the relevant test and checked that it still passes.

fix: use isListedRoute to hide unlisted connecting routes

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/MorePageTests.kt
androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MorePage.kt
androidApp/src/main/res/values-b+es/strings_ios_converted.xml
androidApp/src/main/res/values-b+fr/strings_ios_converted.xml
androidApp/src/main/res/values-b+ht/strings_ios_converted.xml
androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml
androidApp/src/main/res/values-b+vi/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml
androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml
androidApp/src/main/res/values/strings.xml
iosApp/iosApp/Localizable.xcstrings
iosApp/iosApp/Pages/More/MorePage.swift
iosApp/iosAppTests/Pages/Settings/MorePageTests.swift

_Ticket:_ [Display build number somewhere in app](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209527076283999)
I remember being skeptical that this was a two point ticket, and behold, it took an hour.
iOS
android
Added a UI test on each platform. Checked that the value is actually read from the correct place and should have the correct value in real builds.

feat: tap version number to show build number

---

gradle/libs.versions.toml
shared/build.gradle.kts
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/cache/ResponseCache.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/AppModule.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/fs/JsonPersistence.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/SystemPaths.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/cache/ResponseCacheTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/fs/JsonPersistenceTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/mocks/MockJsonPersistence.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/GlobalRepositoryTest.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/RailRouteShapeRepositoryTest.kt

_Ticket:_ [🤖 | Notifications | persist notification windows](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211295242617965?focus=true)
This will simplify moving the favorites storage from preferences to a dedicated JSON file.
iOS
android
Checked that the existing tests pass. Added new tests for the new abstraction.

refactor: encapsulate JSON I/O

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/FavoritesRepository.kt
shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/FavoritesRepositoryTest.kt

_Ticket:_ [🤖 | Notifications | persist notification windows](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211295242617965?focus=true)
Nice and self-contained.
iOS
android
Added new tests for the migration logic.

feat: store favorites in a separate JSON file

---

iosApp/iosApp/ComponentViews/StopListRow.swift
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModel.kt

_Ticket:_ [[QA & release track this trip]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211412336640357?focus=true)
Address the actionable changes from iOS QA.
* Minor padding tweak on trip details stop rows
* Address an issue caused by `MapStyleLoaded` being called more frequently by mapbox on iOS, it was always using the set of rail routes even when called on trip or stop details where it should have a more specific filtered list
iOS
android
~- [ ] Expensive calculations are run in `withContext(Dispatchers.Default)` where …

fix(iOS): Track this trip iOS QA

---

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/TestData.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/ProjectUtils.kt

_Ticket:_ [🤖 | Notifications | Sheet favorite section UX changes](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211291334100672?focus=true), tangentially
I tried to add all Orange Line stops to the test data, but then the Android Studio previews were failing because the method that builds the test data was too large.
iOS
android
Checked that the shared tests still pass.

refactor: split test data into methods by object type

---

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/TripDetailsPageTest.kt
shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/utils/TestData.kt
shared/src/jvmMain/kotlin/com/mbta/tid/mbta_app/ProjectUtils.kt

_Ticket:_ [🤖 | Notifications | Sheet favorite section UX changes](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211291334100672?focus=true), kinda
Having only some OL stations was causing issues in the preview and tests for the favorite sheet, but also, not having Forest Hills meant that the trip details test for a southbound OL trip wasn’t showing Forest Hills in its list of downstream stops, only in its direction and headsign, so that test needed to be fixed.
iOS
android
- ~~[ ] Expensive calculations are run in …

chore: add entire Orange Line to test data
