mbta/mobile_app

.envrc.example, iosApp/ci_scripts/ci_post_clone.sh, iosApp/iosApp.xcodeproj/project.pbxproj, iosApp/iosApp.xcworkspace/xcshareddata/swiftpm/Package.resolved, iosApp/iosApp/Analytics/AnalyticsProvider.swift, iosApp/iosApp/Analytics/ScreenTracker.swift, iosApp/iosApp/ContentView.swift, iosApp/iosApp/IOSApp.swift
_Ticket:_ [Remove appcues](https://app.asana.com/0/1205732265579288/1208355161933381/f)
Removes all usage of appcues 👋  
After this is merged I'll go into XCC and remove the env vars.
App builds and runs without issue on both staging and prod
=> feat: Remove appcues

iosApp/iosApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
This got accidentally included in a commit and is causing pipelines to fail (we should really fix the issue where it deletes itself constantly...)
=> fix: Add back Package.resolved

iosApp/iosApp/Info.plist
No ticket
Create a new release
=> chore: bump version to 1.0.6

iosApp/iosApp.xcodeproj/project.pbxproj, iosApp/iosApp/ComponentViews/DirectionLabel.swift, iosApp/iosApp/ComponentViews/LoadingCard.swift, iosApp/iosApp/ComponentViews/PredictionText.swift, iosApp/iosApp/ComponentViews/UpcomingTripView.swift, iosApp/iosApp/DummyTestAppView.swift, iosApp/iosApp/Localizable.xcstrings, iosApp/iosApp/Pages/AlertDetails/AlertDetails.swift, iosApp/iosApp/Pages/TripDetails/TripDetailsHeader.swift, iosApp/iosApp/Pages/TripDetails/VehicleCardView.swift
~No ticket.~ [Set up list of supported languages](https://app.asana.com/0/1205425564113216/1206811204793714/f), plus adds some more descriptive comments to obscure text strings present in the app so that translators have more context. 
It also adds the missing target supported language tags.
=> doc: Add localization comments + planned languages

iosApp/iosApp/Info.plist
No ticket - version bump for new release.
=> chore: version 1.1.0

iosApp/iosApp/Info.plist
No ticket, bumps version to pickup hot fix for red line disruption in https://github.com/mbta/mobile_app/pull/544
=> chore: version 1.1.1

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/search/SearchBarOverlayTest.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/RoutePill.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/search/results/StopResultsView.kt, androidApp/src/main/res/drawable/stop_bus.xml
_Ticket:_ [🤖 | Search | Search bar UI](https://app.asana.com/0/1205732265579288/1208839363050259/f)
Brings the Search Results styling for Stops up to parity with iOS
iOS
android
No automated testing for visual changes.
=> 🤖 | Search | Search bar UI

iosApp/iosApp/ContentView.swift
_Ticket:_ [ | Fix: Extra tab bar when hide maps enabled](https://app.asana.com/0/1205732265579288/1209391330487797)
This fixes an extra tab bar showing up when hide maps is enabled, and also fixes some voiceover behavior where a tab bar is announced even though it isn't visible on the screen. I can't figure out a perfect fix though (see [this figma thread](https://www.figma.com/design/OVO5Z0eYUtnnRvbxsIRpO3?node-id=1193-35157#1140278167)), and though the tab bar is no longer included on the stop page, an extra tab bar is announced on the nearby transit page, and a tab bar is also announced in the search overlay, where no tab bar should be visible. The alternative is that the tab bar is hidden from VoiceOver, but the entire search bar and overlay is too.
iOS
~- [ ] If you added any …
=> fix(iOS): Double tab bar fixes

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/more/MoreViewModelTests.kt, androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/pages/MorePageTests.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreButton.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreLink.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreSectionView.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MorePage.kt, androidApp/src/main/res/values-b+es/strings_ios_converted.xml, androidApp/src/main/res/values-b+fr/strings_ios_converted.xml, androidApp/src/main/res/values-b+ht/strings_ios_converted.xml, androidApp/src/main/res/values-b+pt+BR/strings_ios_converted.xml, androidApp/src/main/res/values-b+vi/strings_ios_converted.xml, androidApp/src/main/res/values-b+zh+Hans+CN/strings_ios_converted.xml, androidApp/src/main/res/values-b+zh+Hant+TW/strings_ios_converted.xml, androidApp/src/main/res/values/strings.xml, shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/morePage/MoreItem.kt
_Ticket:_ [🤖 | More | Dependencies List](https://app.asana.com/0/1205732265579288/1208851006555175)
Adds the software dependencies and licenses to Android.
iOS
android
Updated unit tests and added tests for new navigation behavior.
=> recovered from bad git state software dependency list

.github/workflows/build-android.yaml
_Ticket:_ none
GitHub Actions is the worst CI service I've ever seriously used except for all the other ones.
I'm leaving #811 in place even though it might not have been necessary, because only having to specify the flavor once is nice.
iOS
android
Not testable.
=> ci: fix the actual issue with Android deployment

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt
_Ticket:_ Kind of [Group by direction | Check on old trip headsign issues](https://app.asana.com/0/1205732265579288/1209536961544705/f) since the spirit of the problem is the same as the old Kenmore bug, but also bug report from @boringcactus.
This PR restructures the `addStaticData` step to actually group all routes for a line into a single record. I wrote `addStaticData` originally and had kind of a hard time reading through it, so I did a bit of refactoring to help my own understanding of it and help me isolate where the root of the bug was. 
The refactoring did help to fix the bug a little, but not entirely. The core of the problem is that the map of Line => Patterns was being built at the *child stop* level, so when keying by `LineOrRoute`, the list of routes for …
=> refactor(RouteCardData): simplify addStaticData step while working on GL park st bug

androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/routeCard/RouteCard.kt
_Ticket:_ [🤖 | Group By Direction | Add more examples to previews](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209962608039726?focus=true)
May as well just toss this in, right?
iOS
android
Checked that the previews all render.
=> feat: add full complement of previews to RouteCard

iosApp/iosApp/Pages/StopDetails/StopDetailsPage.swift, iosApp/iosAppTests/Pages/StopDetails/StopDetailsPageTests.swift
_Ticket:_ [iOS | Group By Direction | All trips are shown when navigating from filtered stop details](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210162265230760?focus=true)
This PR includes two fixes: 
1. When navigating from unfiltered stop details => filtered stop details, don't flicker between 3 and all upcoming trips ([slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1747133184066279))
2. When navigating from filtered stop details => unfiltered stop details, don't show the full list of all upcoming trips on initial load
iOS
android
* Ran locally & confirmed issue fixed in both directions
* Added a unit test which isn't great, but will at least create a failure if we change this behavior in the …
=> fix(ios.StopDetailsPage): Fix thrashing when stopFilter changes

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteCardData.kt, shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/model/RouteCardDataTest.kt
_Ticket:_ [Only display additional stop if next 3 trips are different](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210239404411211?focus=true)
This actually was about as straightforward as we expected, I just wasn't finding any good examples in prod to test with early on. I followed the lead of `potentialService` and used `isBus` to determine if it was safe to check the next 2 or 3 upcoming trips. Also moved the 2 and 3 row values into constants, since we were starting to have lots of duplicate magic numbers floating around.
This does not cover the "Service ended" case mentioned in the QA, I think that will need some other special handling, but since that's reliant on the formatting to decide whether service is over, I'm less sure how we'd deal with it.
| Before …
=> fix: Don't show redundant stops if atypical trips aren't visible

shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/AppModule.kt, shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/dependencyInjection/RepositoryDI.kt, shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/Favorite.kt, shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/FavoritesRepository.kt, shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/usecases/FavoritesUsecases.kt, shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/usecases/FavoritesUsecasesTests.kt
_Ticket:_ [🤖 | Favorites | Add new favorites repository](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209816289542481?focus=true)
Adds new repo favorites repo and accompanying usecases. I _think_ this should cover all our usecases.
Added tests for usecases
=> feat: new favorites repo

androidApp/build.gradle.kts, iosApp/iosApp/Info.plist
Version bump to pick up hotfix, to be merged after https://github.com/mbta/mobile_app/pull/1032
iOS
android
=> chore: bump 1.2.5

bin/android-instrumented-test-ci.sh
_Ticket:_ none
https://github.com/mbta/mobile_app/pull/1050 had four consecutive flaky Android instrumented test failures in the merge queue.
shellcheck doesn’t complain, and this is the same function that worked fine in Xcode Cloud.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210425090924778
=> ci: retry Android instrumented tests

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/map/HomeMapViewTests.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/map/HomeMapView.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt, shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModel.kt, shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/MapViewModelTests.kt
_Ticket:_ [🤖 | v1.2.6 QA | Tapping on a search result doesn’t pan map](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210793281349695?focus=true)
Previously, `viewportManager.stopCenter` was only called for the `SelectedStop` event. Now it is also called during the `NavChanged` event. Based on [feedback in slack](https://mbta.slack.com/archives/C062QNAJZ2M/p1752594812853529), I opted to do this with a helper function called within event handling rather than introduce a new `LaunchedEffect`. 
This also updates other minor inconsistencies, like the trip center button missing when navigating from search.
iOS
android
* Ran locally, tapping on various map elements to confirm centering behaved as expected. When tapping on a …
=> fix(shared.MapViewModel): Center on stop when tapping from search result

iosApp/iosApp/Info.plist
* Small bump for the hotfix https://github.com/mbta/mobile_app/pull/1158
iOS
android
=> chore(ios): 1.2.7

androidApp/build.gradle.kts
Bumps android version so we can release https://github.com/mbta/mobile_app/pull/1250
iOS
android
=> chore: android 2.0.1

.pre-commit-config.yaml, README.md, androidApp/build.gradle.kts, buildSrc/build.gradle.kts, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, iosApp/Podfile.lock, iosApp/iosApp.xcworkspace/xcshareddata/swiftpm/Package.resolved, iosApp/iosApp/ComponentViews/NavTextButton.swift, iosApp/iosApp/ContentView.swift, iosApp/iosApp/Pages/Favorites/EditFavoritesPage.swift, iosApp/iosApp/Pages/Favorites/NoFavoritesView.swift, iosApp/iosApp/Pages/Map/AnnotatedMap.swift, iosApp/iosApp/Pages/Map/HomeMapViewHandlerExtension.swift, iosApp/iosApp/Pages/More/MoreLink.swift, iosApp/iosApp/Pages/Onboarding/OnboardingScreenView.swift, iosApp/iosApp/Pages/Search/SearchInput.swift, iosApp/iosApp/Pages/StopDetails/TripStopRow.swift, iosApp/iosApp/Utils/HaloScrollView.swift, iosApp/iosAppTests/Pages/Favorites/EditFavoritesPageTests.swift, iosApp/iosAppTests/Pages/Onboarding/OnboardingScreenViewTests.swift, iosApp/project.yml, settings.gradle.kts, shared/build.gradle.kts, shared/shared.podspec, shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/model/RouteDetailsStopList.kt
_Ticket:_ [Manual dependency updates](https://app.asana.com/1/15492006741476/project/1205425564113216/task/1210210024736992?focus=true)
I’ve also permanently solved our Sentry version mismatch woes, after a silly amount of Gradle wrestling.
iOS
android
Checked that the build still works and that the Sentry version stuff actually works.
=> chore: manual dependency updates

iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitViewTests.swift
_Ticket:_ [ | iOS CI flaky test fix](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211123075072277?focus=true)
This PR rewrites a NearbyTransitViewTest that has been notoriously flaky in CI, failing merges. I rewrote it to explicitly call `callOnChange` like [testRendersUpdatedPredictions](https://github.com/mbta/mobile_app/blob/819e776b0f7f5cd8885da89e18b486c689b57bfe/iosApp/iosAppTests/Pages/NearbyTransit/NearbyTransitViewTests.swift#L506) to reduce flakiness in the timing of this call. 
Potentially, I think we could consider removing any test on `NearbyTransitView` that looks for the text "Suspension", since that is covered by lower-level `RouteCardTests`, and instead this could just test that `NearbyViewModel.loadRouteCardData` is called, …
=> fix?(ios.NearbyTransitViewTests.testNoService): callOnChange explicily in the test

.github/workflows/cache-cleanup.yaml
_Ticket:_ none
Missed a spot in #1278.
Ran this manually, and it works.
=> fix(ci): specify gh cli parameters for cache cleanup

shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/viewModel/ErrorBannerViewModelTest.kt
_Ticket:_ [Improve recurring data error logging](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211209894303552?focus=true)
Network errors already override data errors, so we already only record a recurring data error if the device is online, and #1322 should automatically make the recurring data error spam clear up somewhat. This is a subtle behavior to be relying on, though, so we may as well add an explicit test for it, so that it will continue to be the case.
iOS
android
- ~~[ ] Expensive calculations are run in …
=> test: check that recurring data errors aren’t logged when offline

androidApp/src/main/AndroidManifest.xml, androidApp/src/main/java/com/mbta/tid/mbta_app/android/component/SaveFavoritesFlow.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/util/NotificationPermissionUtil.kt
_Ticket:_ [🤖 | Notifications | request permissions](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211295242617967?focus=true)
Request notification permission upon saving a favorite.
Not sure there's a good way to automate a test for this.
=> feat(Android): Request notification permission

androidApp/src/androidTest/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsViewTest.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/more/MoreViewModel.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/pages/MapAndSheetPage.kt, androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripDetailsView.kt, iosApp/iosApp/Pages/Map/HomeMapViewHandlerExtension.swift, iosApp/iosApp/Pages/StopDetails/TripDetailsView.swift, iosApp/iosApp/ViewModels/SettingsViewModel.swift, iosApp/iosAppTests/Pages/StopDetails/TripDetailsViewTests.swift, iosApp/iosAppTests/Views/HomeMapViewTests.swift, shared/src/commonMain/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepository.kt, shared/src/commonTest/kotlin/com/mbta/tid/mbta_app/repositories/SettingsRepositoryTest.kt
_Ticket:_ [[QA & release track this trip]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211412336640357?focus=true)
Enable track this trip and get rid of the feature flag.
Updated tests to pass, verified that track this trip now shows up by default
=> chore: Remove track this trip feature toggle

androidApp/src/main/java/com/mbta/tid/mbta_app/android/stopDetails/TripHeaderCard.kt
_Ticket:_ [[QA & release track this trip]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211412336640357?focus=true)
Attempt to prevent line breaks within the follow button text.
Checked at larger text sizes and it's fine, couldn't get the "Stopped X stops" waiting to depart state to verify that this resolves that
=> fix(Android): Try to fix follow button overflow
